### ISSUE TITLE
OcvPersonDetection test video "known tracks" incorrect

### ISSUE THREAD

**Issue by cdglasz** [openmpf/openmpf#1026]
The expected output for ocv_person_video.avi is incorrect; the video contains at least 7 people, but the expected output consists of only 2 detections, neither of which actually contain a person. This video is showcased in the original paper, so the component _should_ be able to handle it correctly.

Ideas for potential causes:
- In [this implementation](https://github.com/yifanli8086/tracker) (which ours may be based on) there is a FRAME_RATE configuration parameter set to 9. In our implementation, references to this parameter seem to have been replaced with a hardcoded 25
- It has been shown through testing that video format and resolution can strongly impact accuracy. We may try to locate original video, in the format used by the original authors
- Updating OpenCV from 3.0.0 to 3.4.7 alters the output significantly, it's possible that an older version of OpenCV is required

**Comment by clnowacki** [comment]
OcvPersonDetection component has been archived.
