### ISSUE TITLE
Jobs fail on corrupt quicktime videos

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1032]
From the end user:

> We are having issues again where OpenCV thinks a particular piece of media has TONS of frames because it is corrupt. For example a 2 KB file is being read and thinks it has 52 million frames, and then it reports bad frame size for everyone of them. This resulted into producing millions of activemq messges and filling up over 10 workflow-manager logs.

> The mimeType on the media was video/quicktime with DURATION 26032 and FRAME_COUNT 526359160. No FPS.

> When we run into something like this, I'd like to error out if the metadata doesn't "make sense" i.e. small duration, very large frame count, no fps - not sure if its possible but maybe if it meets this condition AND reading a frame results in an error then mark as errored.

Consider implementing the following checks during media inspection:

```
if ( (FPS  == 0) || (FRAME_COUNT/(DURATION/1000 * FPS) > 2) ) {
   // possibly corrupt media; try to get first, middle, and last frame based on reported FRAME_COUNT
   // if reading any of those frames fails, then error out
}
```

Basically, if the OpenCV-reported frame count is more than twice the calculated frame count based on the media inspection (FFmpeg), then there may be an issue, so we should try to read the frames directly.

Reading the frames in this situation may need to be done sequentially (brute force). @brosenberg42 has stated that seeking to a frame using:

```
set(cv::VideoCaptureProperties::CAP_PROP_POS_FRAMES, newPosition)
```

doesn’t normally work for quicktime videos, which is why we originally implemented fallback frame read strategies in the MPFVideoCapture tool.

**Comment by jrobble** [comment]
Users experienced a similar issue today where running subsense jobs on corrupt < 1 KB `video/quicktime` files resulted in media inspection believing that each file had millions of frames, resulting in thousands of sub-jobs. Each sub-job resulted in a `BAD_FRAME_SIZE` error. This created a major backlog of messages in the `COMPLETED_DETECTIONS` queue and slowed down processing for the whole deployment.

Running `ffmpeg -i` on one of the files produced:

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x251d240] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 216x384): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '7df06d42232700cf24f80827401a014441787f91a9cc7b2c69db6b9c2b40a40c':
  Metadata:
    creation_time   : 2019-07-25T07:47:39.000000Z
  Duration: 00:00:30.03, bitrate: 0 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), none, 216x384, SAR 1:1 DAR 9:16, 10000k tbr, 10000k tbn, 20000k tbc (default)
    Metadata:
      creation_time   : 2019-07-25T07:47:39.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
```

Of note, the `10000k tbr, 10000k tbn, 20000k tbc` values seem quite large. Note that `tbr` corresponds to FPS.

Tika media inspection produced:

```
Content-Length: 891
Content-Type: video/quicktime
Creation-Date: 2019-07-25T07:47:39Z
Last-Modified: 2019-07-25T07:47:39Z
Last-Save-Date: 2019-07-25T07:47:39Z
X-Parsed-By: org.apache.tika.parser.DefaultParser
X-Parsed-By: org.apache.tika.parser.mp4.MP4Parser
X-TIKA:digest:MD5: e9a173ed168b6f2a49d0fef1d7ab7e18
X-TIKA:digest:SHA256: 7df06d42232700cf24f80827401a014441787f91a9cc7b2c69db6b9c2b40a40c
date: 2019-07-25T07:47:39Z
dcterms:created: 2019-07-25T07:47:39Z
dcterms:modified: 2019-07-25T07:47:39Z
meta:creation-date: 2019-07-25T07:47:39Z
meta:save-date: 2019-07-25T07:47:39Z
modified: 2019-07-25T07:47:39Z
resourceName: 7d_f0_7df06d42232700cf24f80827401a014441787f91a9cc7b2c69db6b9c2b40a40c
tiff:ImageLength: 384
tiff:ImageWidth: 216
xmpDM:audioSampleRate: 10000000
xmpDM:duration: 0.0
```

Note the `xmpDM:duration: 0.0` value, which may be an indication that the file is corrupt. 

Once consideration is to allow the user to set system properties for a minimum video file size and FPS. If video files don't meet these thresholds the job immediately ends in `ERROR`. 

Currently we don't get the `xmpDM:duration` value using the default Tika parsers. Instead we use Tika to parse that value from the ffmpeg results. That ffmpeg `Duration` value is valid, as shown in the first output above. Also, further investigation would be required to determine if Tika always provides a `xmpDM:duration` value for all media types. For these reasons, it may be best not to use that as an indication of corrupt media, or us it in conjunction with the FPS and file size.

Note that it may be the case that FFmpeg does not report the FPS for all videos. This, if FPS is not present that should not indicate an error condition.

**Comment by jrobble** [comment]
Further discussion revealed a solution that is simpler than the one discussed in the above post, and should be considered first:

We currently use OpenCV during media inspection of video files to determine the `FRAME_COUNT`. In general, we can just query OpenCV directly to get that information, rather than reading every frame from the video sequentially and counting them. The query is a quick process.

Since we're already in OpenCV land, we should consider doing a sanity check and attempt to read the first frame of the video. If the first frame is empty (which is what resulted in the `BAD_FRAME_SIZE` error described in the above comment) then job should immediately end in `ERROR`. 

Alternatively, we may be able to `grab()` the frame instead of `read()` it and skip the decoding process - although maybe it makes sense to sanity test the decoding part too.

**Comment by hhuangMITRE** [comment]
I remember we've incorporated the media inspection frame check. Let me know if corrupt QuickTime videos still exist. Closing this issue for now, thanks!
