### ISSUE TITLE
Set Subsense motion detection confidence based on relative frame position and region size

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1033]
Currently, the SUBSENSE component assigns a confidence of -1 (the default) to all detections. This is not useful. Users have expressed a desire to use the `FEED_FORWARD_TOP_CONFIDENCE_COUNT` property when handling feed-forward motion tracks.

Consider the following calculation:

```
confidence = (norm(distance from center frame of track) + (ratio of bounding box size to largest bounding box)) / 2
```

Here, each of the values in the sum are individually in the range 0-1, thus we have to divide by 2.

To allow for greater flexibility, allow the user to weight each part of the summation individually by exposing the weight factors as configurable properties:

```
confidence = norm(DISTANCE_WEIGHT_FACTOR * norm(distance from center frame of track) + SIZE_WEIGHT_FACTOR * (ratio of bounding box size to largest bounding box))
```

Make sure to normalize the confidences over all of the detections in the the track (take each un-normalized value and divide by the sum of the un-normalized values).

**Comment by clnowacki** [comment]
This has been completed for the Subsense motion component. It still needs to be implemented for the MOG motion component.
