### ISSUE TITLE
Add support for COULD_NOT_OPEN_MEDIA and COULD_NOT_READ_MEDIA error types

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1086]
Create a new `COULD_NOT_READ_MEDIA` error that is used instead of `COULD_NOT_READ_DATAFILE` when media cannot be accessed. The latter should only be used for accessing model files, configuration files, etc. Update all of the component APIs to support it. This also requires updating the Protobuf messages. 

Of note, the `MPFImageReader` and `MPFVideoCapture` tools will need to be updated to return this new error type.

Also, check the components to see when they generate `COULD_NOT_READ_DATAFILE` and if returning `COULD_NOT_READ_MEDIA` is more appropriate.

Additionally, use `COULD_NOT_OPEN_MEDIA` instead of `COULD_NOT_OPEN_DATAFILE`, if appropriate.

**Comment by brosenberg42** [comment]
OpenCV doesn't tell you why it couldn't open a media file. If OpenCV doesn't open the media file, then we should check if the file exists and is readable by the current process.
