### ISSUE TITLE
Configure Camel not to auto-ack messages

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1094]
Looking at `applicationContext-jms.xml`, I see that `transacted` is `false` and that `acknowledgementMode` is not explicitly set. The default value is `AUTO_ACKNOWLEDGE`.

Unlike WFM --> component communication, where we explicitly `commit()` the session when we're done processing a sub-job message, it seems that WFM --> WFM communication, which is all handled by Camel, is auto-acknowledged. I believe this means that the message is removed from the pending state as soon as the message is received by the consumer before we start processing it.

The end users would rather be able to see messages left in the pending state in ActiveMQ so that they can better track when jobs are stuck in the media inspection phase, or other phases of the job lifecycle.

**Comment by hhuangMITRE** [comment]
Done, updated Camel to CLIENT_ACKNOWLEDGEMENT MODE.
