### ISSUE TITLE
C++ component executor has memory leaks

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#1104]
According to Valgrind, the following lines allocate memory that is never free:
* https://github.com/openmpf/openmpf/blob/fbae325067c1872074202ce07c4135a62c57a164/trunk/detection/executor/cpp/batch/MPFMessenger.cpp#L168
* https://github.com/openmpf/openmpf/blob/fbae325067c1872074202ce07c4135a62c57a164/trunk/detection/executor/cpp/batch/MPFMessenger.cpp#L193

**Comment by jrobble** [comment]
Good find. I took a quick look and those do seem like memory leaks. They don't seem too hard to fix.
