### ISSUE TITLE
Update REST API doc with media metadata field

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1148]
Related to https://github.com/openmpf/openmpf/issues/1100.

**Comment by hhuangMITRE** [comment]
I've made the updates for the REST API doc and will copy the changes over to the develop branch once the PR for `skip-media-inspection` lands.

In the meantime, I've placed the documentation update in https://github.com/openmpf/openmpf.github.io/tree/skip-media-inspection-docs, which will be removed once the I'm ready to push the official changes in.

**Comment by hhuangMITRE** [comment]
Done. Changes landed to develop.
