### ISSUE TITLE
Improve Tesseract OSD fallback behavior

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1152]
With the current behavior it's possible to select the OSD rotation from the fallback pass without the OSD script from the fallback pass. This can result in situations where the detection has a reported rotation value that does not make sense for the reported script. For example, Latin is sometimes detected as Bengali with it's rotated 180 degrees. Reporting a 180-degree rotation with Latin script is invalid in that case. 0-degree rotation with Latin, or 180-degree rotation with Bengali are more acceptable.

**Comment by hhuangMITRE** [comment]
Jenkins builds completed successfully and I've landed the changes to both master and develop branches.
