### ISSUE TITLE
Support Azure Cognitive Services Form Recognizer API

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1161]
Create a component that uses the [ACS Form Recognizer API](https://azure.microsoft.com/en-us/services/cognitive-services/form-recognizer/). Users are most interested in the Layout model to return information about document tables. Return one track per document page. Each track can consist of separate detections:

- One detection for each table on the page. The text results in the JSON output object should be in CSV format.
- One detection per track for all of the key-value pair data on the page.
- One detection for each string (text chunk), or other type of data.

Each detection should contain a detection properties entry that denotes what kind of detection it represents (e.g. `TABLE`, `KEY-VALUE PAIRS`, etc.).

---

**Update 9-8-2020**

Support [Form Recognizer v2.1](https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/language-support).

---

**Update 9-22-2020**

Add support for the receipts model and add support for key-value pair outputs. Also, add support for custom models.

Determine how the API handles different language inputs.

**Comment by hhuangMITRE** [comment]
Sounds good. The string output is divided into lines and then words (each set of words associated with a particular line output). From their documentation/code, this result appears as an optional setting, but I assume we'll want to include this when it's available. I'll separate them in `LINE` detection outputs as discussed.
