### ISSUE TITLE
Create component for Azure Cognitive Services Read API

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1162]
Create a component that uses the [ACS Read API](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/concept-recognizing-text#read-api). Users are most interested parsing hand-written documents.

This is not to be confused with the [ACS OCR API](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/concept-recognizing-text#ocr-api), for which we already have an existing component. That component supports structured (printed) text, not hand-written text. The Read API supports both kinds of text and seems to be shaping up to be a replacement for the OCR API, and although it does a lot more than the old API, it does not support as many [languages](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/language-support#optical-character-recognition-ocr). Note that both support Spanish, among others.

In the future, we may decide to retire supporting the OCR API in favor of the Read API, but until we know for sure there is no benefit in the OCR API over the Read API, we should support both.

**Comment by hhuangMITRE** [comment]
Brian has helped review and land the PR. Assuming we'll continue to support both ACS OCR and Read APIs in the meantime. There will likely be more updates for the latest OCR/Read API from Microsoft and those can go into our ACS Read Text Detection Component.
