### ISSUE TITLE
Investigate DoubangoTelecom ultimateMICR-SDK for bank check detection

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1202]
Investigate [DoubangoTelecom ultimateMICR-SDK](https://github.com/DoubangoTelecom/ultimateMICR-SDK) for bank check detection. Determine if we want to use that TensorFlow implementation and/or their [Tesseract model](https://github.com/DoubangoTelecom/tesseractMICR).

**Comment by jrobble** [comment]
Currently blocked pending user feedback.

**Comment by hhuangMITRE** [comment]
Unlikely to move forward at the present time.
