### ISSUE TITLE
Allow job properties that don't change during service lifetime to be set using environment variables

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#1206]
Modify the component executors to look for environment variables with the `MPF_PROP_` prefix and add them as job properties. Properties defined in this way override existing job properties.

Currently, some components allow particular job properties to be set through environment variables. For example, the Azure components allow `ACS_URL` and `ACS_SUBSCRIPTION_KEY` to be set as environment variables. The current behavior is undesirable because every component that needs this behavior must implement it themselves for each property.

**Comment by jrobble** [comment]
From @jrobble:

> We talked about this before and I'm coming back to the same conclusion. It would be best if a job property could take precedence over the env. var., but env. var. takes precedence over the default alg. prop., but since the component executor has no way to know which props are job props, alg. props, etc., there's not much we can do without changing the component API or passing additional info in the job request protobuf.
> 
> In the TRTIS component descriptor.json `TRTIS_SERVER` is set to the blank string. In the code we only use the env. var. value if the property is not in the job struct or the job struct property is equal to the empty string. If the property is not specified anywhere (or is in the job struct but equal to the empty string), we default to localhost. This enables the job property to take precedence over the env. var. I don't like how the property is defined as the empty string in the descriptor.json, but localhost is actually the default value.
> 
> We rationalized your approach by saying that properties should only really be specified as env. variables for things that will not change during the lifetime of the component container, such as a server host/port.
