### ISSUE TITLE
Detect objects in PDFs T2293

### ISSUE THREAD

**Issue by Angrymute** [openmpf/openmpf#124]
There is a need to perform detections on images that appear on pages of PDF documents. For all intents and purposes, a component can process each page of the PDF as a separate image job.

Tracking objects across pages does not make sense. The location of an object on a page is not relevant.

The following approach affords the best flexibility while not over-complicating the WFM:

Implement a PDF pre-processor component to convert a PDF into a series of images.
Each image job will be passed a mediaMetadata property that indicates which page of the PDF the image corresponds to. This information will flow through the WFM and be used by the post-processor component.
The next stage(s) of the pipeline will handle each page of the PDF as a separate image.
Implement a post-processor component to aggregate the image detection results of the previous pipeline stage into a single media element (tagged with the name of the PDF) in the JSON output.
Pros:

Current detection components do not have to be aware that they are processing a PDF.
Only the pre-processor needs to implement support for the PDF data type.
All other components will inherit a default implementation of getDetections(MPFPdfJob) that returns a data type not supported error.
Does not require sprinkling many modifications across the WFM source code.
Pre-processor handles the PDF to image conversion. Can be written in Java or C++.
Cons:

Requires users to create custom pipelines for PDFs, but this may already be expected.
Considerations:

Perform markup after post-processor?
If a developer wants to write a component that directly accesses the PDF (to OCR it, for example), they can implement support for the PDF data type.

**Comment by jrobble** [comment]
Processing of PDFs is being handled by @hhuangMITRE by using the generic detection API.
