### ISSUE TITLE
Check detection width and height before tagging as SHRUNK_TO_NOTHING

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1256]
If a detection has 0 width or height prior to applying padding, then don't apply the `SHRUNK_TO_NOTHING` property. That's confusing. It makes the user think the detection region was shrunk when in reality it already had an area of 0.

**Comment by clnowacki** [comment]
With the changes to the DetectionPaddingProcessor to remove ill-formed detections, detections with zero width or height will be removed from the track before padding is applied.
