### ISSUE TITLE
Update WFM to label stationary vs. non-stationary tracks

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1258]
Users have the need to identify tracks that aren't in motion. Even if motion preprocessing is used, often detection components will be asked to process frame data with stationary objects in the background even when the intent is to operate only on the frame data with objects in motion.

To address this, the WFM should support a property to enable labeling stationary vs. non-stationary objects. This can be accomplished by getting the average bbox for a track and counting number of detections in the track that have an IoU less than some user-defined threshold with the average bbox.  If the count is greater than some user-defined N, consider the track to have motion.

Support the following new WFM properties:
- Property to determine if tracks should be labelled stationary or non-stationary
- Property to set the IoU threshold
- Property to set the N detections required to consider the track to have motion
- Property to drop stationary tracks

**Comment by hhuangMITRE** [comment]
WFM track labeling landed to `develop`.
