### ISSUE TITLE
Update Tesseract component to support videos

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1285]
Update the Tesseract component to support videos in addition to images.

> "step 1 is just run tesseract on key frames of video"

This can be accomplished by setting the job property `USE_KEY_FRAMES=true`. MPFVideoCapture will then only read key frames.

Note that EAST already supports videos. We will probably need an EAST --> Tesseract pipeline.

**Comment by hhuangMITRE** [comment]
Update: Currently in discussion to see if we want to add parallel frame processing for videos.

**Comment by jrobble** [comment]
Decided to postpone this task in favor of higher priority items for now.
