### ISSUE TITLE
Use MPF_BAD_FRAME_SIZE instead of MPF_DETECTION_FAILED for OpenCV empty/resize exception

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1337]
When the OpenCV DNN component gets a zero-size detection from the previous stage it will generate a job error like the following:

```
            {
               "source": "DNNCV",
               "code": "DETECTION_FAILED",
               "message": "OpenCV raised an exception while trying to get detections from video: OpenCV(4.5.0) /tmp/opencv/opencv-4.5.0/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'\n (Frames: 20453 - 31576)"
            }
```

---

After discussion, it may be best to address this in the WFM by removing zero-sized detections from tracks before generating segments for the next stage. 

This should instead use the `MPF_BAD_FRAME_SIZE ` error code when the exception is thrown due to a resize call. That will allow end users to make a more informed decision about what to do since `MPF_DETECTION_FAILED` is a generic catch-all error code. 

Look for other instances where the resize call is made in other components.

**Comment by clnowacki** [comment]
As an extra measure, update the workflow manager DetectionPaddingProcessor to remove any zero-size detections from tracks before padding.
