### ISSUE TITLE
Upgrade to OpenCV 4.5.5

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#1519]
Certain corrupt media files can cause Workflow Manager to crash. Upgrading OpenCV allows Workflow Manager to detect the corrupt video and prevent further processing.

**Comment by jrobble** [comment]
We determined that although most Python components have `opencv-python>=4.4.0`, that is sufficient to allow OpenCV to detect the corrupt video that motivated the C++ OpenCV upgrade to 4.5.5.

Specifically, the earliest match is `opencv-python==4.4.0.40` and that fails to read the frame w/o crashing.

Linking to different ffmpeg libraries also fixes the issue. We saw that when @brosenberg42 determined the Ubuntu version of the OpenMPF WFM detects the issue.

Most likely, the Python version of OpenCV is linking to a different version of ffmpeg, while allows it detect the issue although it's an older version of OpenCV.
