### ISSUE TITLE
Test frame resolution change with OpenCV videoCapture

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#167]
Test what happens to an OpenCV videoCapture if the frame resolution changes. Will it just work seamlessly, or would it do something unexpected like always return frames with whatever the original resolution was? We don’t know how the underlying decoders work, or whether or not they would simply crash if the stream changed out from underneath them.

**Comment by clnowacki** [comment]
Do you have suggestions on how to test this? I think the reason I've never tested it before is that I don't know how to change video resolution mid-stream. Any ideas would be welcome.

**Comment by clnowacki** [comment]
This link (from an email from @jrobble about this topic) has some clues about how to do this with H.264 video. http://forum.doom9.org/showthread.php?p=1371407#post1371407

**Comment by jrobble** [comment]
I would start by concatenating multiple H.264 encoded mpeg-4 videos (of different resolutions) together end-to-end using FFmpeg. Before using OpenCV I would try playing the video in VLC, ffplay, and possibly other programs to see how they handle it.

**Comment by jrobble** [comment]
New information has come to light. Users will be providing separate SD and HD streams, so this is a non-issue.
