### ISSUE TITLE
Investigate how the WFM will create sub-jobs for feed-forward batch processing

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#176]
Let's define a sub-job as an MPFImageJob, MPFVideoJob, or MPFAudioJob. When the WFM gets a request to create a new batch job through the REST API, it creates Camel routes and starts the process of executing that job. An important part of the process involves splitting the job in sub-jobs. Each sub-job is passed to component services via a component-specific job request queue.

Generally, sub-jobs are created for two reasons:

1. There is at least one sub-job for piece of media. For example, there will be one MPFImageJob for every piece of image media in the batch job request.

2. There is one sub-job for each segment in a video. For example, for a 10,000 frame video the WFM will generate 10 MPFVideoJobs if the segment size is set to 1,000 frames.

The WFM is also responsible for discarding small tracks (configurable: MIN_TRACK_LENGTH) and merging tracks (configurable: MERGE_TRACKS) after every stage of the pipeline. Two tracks are merged if if the gap (number of frames) between two merged tracks is small enough (configurable: MIN_GAP_BETWEEN_TRACKS) and the detection region overlap % is above some threshold (configurable: MIN_OVERLAP).

For each of these merged tracks, the WFM generates segments for the next stage by first sorting the merged tracks by time and then combining / splitting them based on MIN_GAP_BETWEEN_SEGMENTS, TARGET_SEGMENT_LENGTH, and MIN_SEGMENT_LENGTH. Refer to the "Segmenting Media" section in the [User Guide](https://openmpf.github.io/docs/site/User-Guide/) for more information.

For feed-forward processing, the WFM needs to ensure that each new segment corresponds to a merged track generated in the previous pipeline stage. This will require by-passing some of the segmenting logic discussed in the "Segmenting Media" section. If the segment is larger than the desired segment size, then it's acceptable for the segment to be split into two smaller segments. This still ensures that each new segment corresponds to one merged track.

Ultimately we want to ensure that the WFM only needs to pass one track (or part of one track) generated in the previous stage to the sub-jobs in the next stage. 

Note that if the "FEED_FORWARD_TYPE" job/algorithm/media property is not set (or set to "NONE"), then the WFM creates sub-jobs normally (current behavior). This new behavior only takes effect if the "FEED_FORWARD_TYPE" property is set to something else.

Assess the feasibility of this approach.

**Comment by jrobble** [comment]
The WFM will be responsible for generating segments based on the value of FEED_FORWARD_TOP_CONFIDENCE_COUNT. It will need to sort the detections in a track by confidence. To do this, it can use a Java [PriorityQueue](https://docs.oracle.com/javase/8/docs/api/java/util/PriorityQueue.html).

**Comment by jrobble** [comment]
The WFM should remove the FEED_FORWARD properties from the job properties map when generating the sub-job for the first stage of the pipeline. This way, the MPFVideoCapture tool in the first stage can handle the FRAME_INTERVAL normally. 

The MPFVideoCapture tool will ignore the FRAME_INTERVAL property if one or both of the FEED_FORWARD properties is set. This may be the case for any pipeline stage after the first one.

**Comment by jrobble** [comment]
The WFM should ensure that the feed-forward track passed as part of a sub-job only contains the detections that sub-jobs needs to process. The start frame for that sub-job should correspond to the index of the first detection in the track, and the stop frame should correspond to the last detection in the track.

**Comment by jrobble** [comment]
The WFM should also handle the feed-forward for image jobs. Consider the case where more than one person is detected in the first stage for a given image. The WFM should take each of these detections and generate a separate feed-forward sub-job for the next stage, which may be face detection.

**Comment by jrobble** [comment]
We need to think about how the WFM will handle feed-forward for audio jobs. Generally speaking, the behavior should be similar to how the WFM handles image jobs: For each audio track in the first stage, generate a sub-job using that track for the next stage. The WFM does not currently perform segmenting on audio files, so the feed-forward behavior is not as complex as it is for video files.

**Comment by dpierce17** [comment]
Currently looking into this with the understanding that the DetectionSplitter is the WFM start point for kicking off sub-jobs.  Betsy had previously mentioned this, and comments in DetectionSplitter includes: "DetectionSplitter will take in Job and Stage(Action), breaking them into managable work units for the Components" so I think I'm on the right track.  The DetectionSplitter gets Tracks from REDIS, has access to current stage via the performSplit method parameters transientJob:getCurrentStage() and transientStage (question: would these two return the same stage?), has access to job, algorithm and media properties and uses those properties to create what is called a SegmentingPlan, eventually creating a detectionRequestMessages List that is returned to the caller, presumably to be sent to a message queue.  Would these detectionRequestMessages eventually be consumed by the Components?  This class also constructs a DetectionContext from TimePairs (note: these TimePairs would have to be adjusted for feed-forward processing.  Support software for this was already added to support OpenMPF Issue #215).  
FYI, I couldn't find any documentation describing the communication between WFM and the Components, so I'm making a guess as to the starting touch point for support of feed-forward.  Question to Jeff and Brian, am I on the right track with looking at DetectionSplitter?

**Comment by jrobble** [comment]
> the DetectionSplitter is the WFM start point for kicking off sub-jobs

Yes, that's my understanding.

> transientJob:getCurrentStage() and transientStage (question: would these two return the same stage?)

Looking at the code, `TransientJob.getCurrentStage()` returns an int which represents the index of the stage in the pipeline. `TransientStage` is an object. 

To get the `TransientStage` from the `TransientJob` it seems like you can do `TransientJob.getPipeline().getStages().get(TransientJob.getCurrentStage())`. I'm not sure if it would ever be necessary to do that though.

> Would these detectionRequestMessages eventually be consumed by the Components?

Yes.

> am I on the right track with looking at DetectionSplitter

Yes, in general it seems like you're on the right track.
