### ISSUE TITLE
Update GPU Support Guide to use CMAKE_CUDA_FLAGS

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1775]
Currently, the guide instructs developers to use `CUDA_NVCC_FLAGS`. Update it to use `CMAKE_CUDA_FLAGS`. For example;

```
    string(APPEND CMAKE_CUDA_FLAGS
        " --gpu-architecture=compute_52 --gpu-code=compute_52,sm_87")
```

Note, that `CUDA_NVCC_FLAGS` no longer works. From @brosenberg42:

> Earlier versions of cmake treated CUDA like a package and `CUDA_NVCC_FLAGS` works with FindCUDA. The current way to enable cuda is to set the project language. For example: `project(my-face-detection LANGUAGES CXX CUDA)`

**Comment by clnowacki** [comment]
Check the code to make sure we are building this way.

**Comment by clnowacki** [comment]
As discussed, remove language about specific nvcc codes and give more general guidance on building OpenMPF components for GPU.
