### ISSUE TITLE
Update Ansible deployment scripts to retain existing jobs when using SEQUENCE for the job ids

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#188]
Update the Ansible deployment scripts to run the commands identified in https://github.com/openmpf/openmpf/issues/181 when upgrading from a batch-only version of OpenMPF.

[This is the ansible script](https://github.com/openmpf/openmpf/blob/develop/trunk/ansible/install/ansible/roles/upgrade/tasks/8to9/mysql.yml) that's used to make updates to the DB when upgrading OpenMPF 0.8.0 to 0.9.0. We need a similar script when upgrading from OpenMPF 1.0.0 to 2.0.0, for example: openmpf-projects/openmpf/trunk/ansible/install/ansible/roles/upgrade/tasks/1.0.0-to-2.0.0/mysql.yml.

Looking at openmpf-projects/openmpf/trunk/ansible/install/ansible/roles/upgrade/tasks/8to9/mysql.yml, I don't like the "8to9" directory name. It's unclear if those are major or minor versions. Instead we should rename that directory to "0.8.0-to-0.9.0".

**Comment by dpierce17** [comment]
Issue: the bash script to update MySQL for hibernate sequence #181 works fine when working with already deployed mpf software, the bash script to update the hibernate_sequence.next_val values has to be run after workflow-manager starts in tomcat (because both job_request and streaming_job_request (i.e. 2 tables) will be using the 2 rows in hibernate_sequence.next_val.  So, the ansible playbook which runs the bash script to update mpf.hibernate_sequence.next_val values has to be run after workflow-manager starts in tomcat.  Part of this task is to find out where the insertion point for the new ansible playbook in the ansible update scripts.

**Comment by dpierce17** [comment]
Update on previous issue: the bash script to update mpf.hibernate_sequence.next_val values has to be run after workflow-manager starts in tomcat, this task should only be run on the mpf-master.  The correct insertion point looks to be in mpf-master.yml.  Will add running the update mpf.hibernate_sequence.next_val bash script as the last post_task.

**Comment by jrobble** [comment]
In mysql.yml there is a one-liner:

```
  - name: Set output_object_version for existing entries in mpf.job_request table
    command: >
      mysql --execute="update mpf.job_request set output_object_version = '{{ r8OutputObjectVersion }}' where output_object_version is NULL;"
    when: check_output_object_version|succeeded
```

I believe that your command can also be written as a one-liner, so a bash script won't be necessary. @brosenberg42 has more info on how to do that.

**Comment by dpierce17** [comment]
The one liner that I’ll be using is:

update mpf.hibernate_sequence set next_val=(SELECT IFNULL( (SELECT max(id)+1 FROM mpf.job_request), 1)) ;

I already added this update to issue #181

                Regards,
                Debbie

**Comment by jrobble** [comment]
@dpierce17, sounds good. Why is the above comment formatted like an email?

**Comment by dpierce17** [comment]
For this task, will add cleanup of the mpf specific executables, jars and libs prior to installing the mpf software.  Will do this by adding a new mpf-clean ansible playbook.  The correct placement for this looks to be in push-configuration.sh, before the call to run-install.py.

**Comment by dpierce17** [comment]
Update, it was found that mpf version 0.10.0 is also referenced in many pom.xml files.  Some of the pom.xml files that needed to be changed reside in the openmpf-components repo and in the openmpf-java-component-sdk repo, in addtion to the openmpf repo.  Creating similarly named feature branch update_ansible_branch_092517 in all repos, each will require separate pull requests.

**Comment by dpierce17** [comment]
Update, some .json description files were also found to include the mpf version number.  Need to update openmpf-projects/openmpf/trunk/workflow-manager/src/main/resources/templates/nodeServicesPalette.json and openmpf-projects/openmpf-components/java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json

**Comment by dpierce17** [comment]
Update, componentVersion and middleWareVersion should be updated to R1.0.0 as well

**Comment by dpierce17** [comment]
Update: during testing, found that /opt/mpf/data/nodeServicesPalette.json and /opt/mpf/data/nodeManagerConfig.xml should be cleaned out prior to re-installing mpf.  By deleting those files during cleanup we can be sure that the WFM starts with a blank slate and can then copy over the necessary template files.

**Comment by dpierce17** [comment]
Adding backup and removing of previous version of MPF Component Archives to this task
