### ISSUE TITLE
Separate out each component into a subrepo

### ISSUE THREAD

**Issue by lewisloren** [openmpf/openmpf#2]
Components should not be packaged in the same .tar.gz as the MPF core. To date we've been delivering source code that includes the MPF core source code and the source code for all of the components. Moving forward we should provide the source code for components separately from the MPF core source code. This provides for greater flexibility and allows us to keep the MPF core source code clean and ready to be shared.

**Comment by jrobble** [comment]
This task is no longer valid. Components will now be placed into the openmpf-components repo or the openmpf-contrib-components repo.
