### ISSUE TITLE
Handle cleaning up after streaming video jobs

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#213]
Refer to the commented-out code in trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java in `cancel()`. Address the `TODO`s that handle cleanup.

**Comment by dpierce17** [comment]
Need to add and test software that will actually clean up after a streaming job if requested during a cancel streaming job request.  Implementation will assume that Components can handle removal of streaming job files and directory while still processing (i.e. before cancel request is processed by Component).

**Comment by dpierce17** [comment]
Closed, landed in PR #250
