### ISSUE TITLE
Update TimeUtils.java to support feed-forward batch processing

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#215]
Update TimeUtils.java to support generating segments when feed-forward is enabled. Currently, `TimeUtils.createSegments()` does not take into consideration the value of FEED_FOWARD_TYPE nor FEED_FORWARD_TOP_CONFIDENCE_COUNT. Either update this method or create another method.

When generating feed-forward segments, chose the segment start frame and stop frame such that the greatest number of detections with the highest confidence (<= FEED_FORWARD_TOP_CONFIDENCE_COUNT) are captured within each segment. In some cases, it may make sense to generate segments where the value of (start frame - stop frame) exceeds the value of the segment size property if the top-confidence detections in that segment are spaced out. This is because only the frames associated with top-confidence detections will be processed, so only those frames count against the desired segment size.

Add unit tests to TestSegmenting.java to test the TimeUtils updates.

<br>**UPDATE 9/1/17:**

**When feed-forward is enabled, we should generate one segment for the whole feed-forward track.**

**Comment by dpierce17** [comment]
While researching this task, found that the implementation of TimePair Comparable (method compareTo) needs to be fixed.  Added that fix to this task along with correcting TimePair hashCode method to use Objects.hash()

**Comment by dpierce17** [comment]
While working this task, found a bug in DetectionSplitter:createTimePairsForTracks.  In this method, a 1 was added to track.getEndOffsetFrameInclusive() when forming the TimePair.  Research shows that track endOffsetFrame used to be exclusive (hence the +1), but the +1 is no longer required now that endOffsetFrame is inclusive.  Fixing this bug as part of this task.

**Comment by dpierce17** [comment]
Also found that the Comparable for Detection was not fully implemented, only check was for other Detection equal to null (if so returned the other Detection as greater than this Detection), or for other Detection equal to this Detection.  Keeping original assumption that a null Detection is after this Detection (i.e. maybe the original intent was to mark end of data set?), and adding correct less than and greater then checks.
