### ISSUE TITLE
Investigate OpenCV issue with setting frame position.

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#217]
Depending on the video, OpenCV appears to be unable to correctly set the frame position of the video when calling `bool cv::VideoCapture::set(cv::CAP_PROP_POS_FRAMES, double  value)`.

- Do some research online to determine if there is work-around.

- Experiment with using different back ends (http://docs.opencv.org/3.2.0/d4/d15/group__videoio__flags__base.html#ga023786be1ee68a9105bf2e48c700294d).

- Do some bench-marking to determine if repeatedly calling `bool cv::VideoCapture::grab()` is a viable solution.

**Comment by jrobble** [comment]
Is this done?

**Comment by brosenberg42** [comment]
Yes. MPFVideoCapture is being updated to use `bool cv::VideoCapture::set(cv::CAP_PROP_POS_FRAMES, double value)` when possible and fallback to slower methods when that fails.
