### ISSUE TITLE
Update OpenCV to 3.3.

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#220]
Currently we're using OpenCV 3.2. Updating FFmpeg requires recompiling OpenCV, so while we're working on #219 we should investigate the difficulty of updating to OpenCV 3.3, which is the latest and greatest.

**Comment by brosenberg42** [comment]
We probably want to enable the C++ 11 features when we compile.

> OpenCV can now be built as C++ 11 library using the flag ENABLE_CXX11. Some cool features for C++ 11 programmers have been added.
