### ISSUE TITLE
Apply system properties without restarting the web app

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#224]
OpenMPF reads many system properties during initialization. Changing some of them on the fly can result in inconsistent state. Thus, when a system property is changed through the web UI we show a banner notification stating that the web app must be restarted for the changes to be applied.

We should look into a way to apply these updates without restarting the web app. The restart is inconvenient for end users because it will result in cancelling jobs that are currently running.

Specifically, users are interested in changing the following properties without restarting the web app:

- detection.confidence.threshold
- detection.sampling.interval       
- detection.segment.minimum.gap            
- detection.segment.minimum.length      
- detection.segment.target.length             
- detection.track.merging.enabled             
- detection.track.min.gap
- detection.track.minimum.length             
- detection.track.overlap.threshold

The user is primarily interested in detection.sampling.interval, but we should support all of the detection.* properties, even those not listed above.

**Comment by jrobble** [comment]
One problem is that some WFM classes may read the value of data members from `PropertiesUtil` once when they are initialized, so even if the value in `PropertiesUtil` is updated that won't change the value used by those classes.

Depending on the system properties that we allow to be dynamically updated, these classes may have to be modified to always read property values from `PropertiesUtil` rather than storing values as internal data members.

**Comment by jrobble** [comment]
Restarting the WFM application context is not an option because it will result in tearing down existing jobs.

**Comment by jrobble** [comment]
It may be worth considering using `PropertiesUtil` to populate system properties in Redis on startup, and then using Redis to manage those system properties while the WFM is running. Existing classes will need to be updated to use Redis to get the system property values.

**Comment by brosenberg42** [comment]
Redis gets flushed when Workflow Manager starts up. What benefit do we get by storing the properties in Redis over just storing them in memory? It sounds like we would have to access Redis every time we want to access a property value.
A simpler way to do this would be to retain the current behavior that writes to mpf-custom.properties, and at the same time the file is updated, also set the value in PropertiesUtil.

**Comment by jrobble** [comment]
I agree that either way we'd have to write out the mpf-custom.properties file. When it comes down to it, storing the properties in Redis is simply another way to store them in memory. Either we get the values via `PropertiesUtil` or `RedisImpl`. I could go either way. It's probably simpler to stick with what we're already doing in `PropertiesUtil`.

Generally speaking, since only one process is ever using Redis, there's not a lot of value in it - it seems like it could be replaced by Java classes. Either data is occupying JVM memory or Redis memory. It's all RAM under the hood.

**Comment by dpierce17** [comment]
Jeff, you had asked me to work this task - can you re-assign this issue to me?

**Comment by dpierce17** [comment]
Also, part of this task will include updating the Angular software in AdminPropertySettingsCtrl.js. For example, if a MPF admin changes detection.artifact.extraction.policy there should be an Apply button available to the admin so he can request that the property change be applied in addition to being saved. Also, the behavior of the UI has to be changed for detection properties vs. non-detection properties. If the admin changes a detection property, he shouldn't be prompted to restart the server

**Comment by dpierce17** [comment]
Since I'll be changing the Edit Properties UI, should this include breaking the page up into 2 sections to make it more understandable? I'm proposing breaking up the properties into a dynamic properties section (no restart required) and a immutable properties section (restart required)

**Comment by jrobble** [comment]
> should this include breaking the page up into 2 sections to make it more understandable

I think that would be the clearest. One section could have the label "Default Job Properties" and the other section called "General System Properties".

**Comment by dpierce17** [comment]
Checked usages for all of the PropertiesUtil detection.* properties getter methods, and didn't find any WFM classes that stored those values during initialization - so, changing the values of the detection properties by adding setter methods to PropertiesUtil doesn't appear to be a problem.

**Comment by jrobble** [comment]
> What will the repercussions be if a detection property value is changed at some midpoint of this processing?

Not good. I don't think the job will fail, but the behavior may be unpredictable / undesirable. We should ensure that the same detection.* property values are used throughout the entire lifetime of a job. New values should only affect new jobs.

Let's consider DetectionSplitter.performSplit(). That method is responsible for determining the final set of property values that go into the modifiedMap, and may pull them from the system properties. That method is called before each stage of a pipeline. Thus, if the property values are changed between stages, then the next time performSplit() is called is could use a different sampling interval, which is not desirable.

To get around this, one option would be to create a TransientDetectionSystemProperties class that captures all of the current detection.* system property values when a job is created. We could implement PropertiesUtil.getDetectonProperties(), which would construct and return that class. We could then store that class in Redis, similar to how we store the other Transient* classes. Whenever DetectionResponseProcessor, DetectionSplitter, or TrackMergingProcessor need to get a system property value, it can retrieve it from that class, which it could retrieve from Redis.

Note that when PropertiesUtil.getDetectonProperties() is invoked, it will need to grab a lock to ensure that none of the detection system properties are modified until the TransientDetectionSystemProperties instance is fully constructed. The detection system property setter methods that you plan on adding should use the same lock.

Note that JobCreationProcessor creates the other Transient* classes, but because we need the lock in this case I believe that it makes more sense for PropertiesUtil to create the TransientDetectionSystemProperties instance.

**FYI:**

I believe that when you do to save properties through the web UI it calls AdminPropertySettingsController.saveProperties(). That method does:

```		
try (OutputStream outputStream = propertiesUtil.getCustomPropertiesFile().getOutputStream()) {
    customProperties.store(outputStream, "modified");
}
```

Note that the updated custom properties file is not reloaded until the WFM restarts (which is why we currently require the user to restart the WFM after changing properties).

**Comment by jrobble** [comment]
On a related note, the [algorithms map in PipelineServiceImpl](https://github.com/openmpf/openmpf/blob/develop/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineServiceImpl.java#L70) will need to be refreshed when the detection system properties are updated. [Some algorithm descriptor files](https://github.com/openmpf/openmpf-components/blob/develop/cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json#L49) use a propertiesKey so that the default value of a property is pulled from a system property. PipelineServinceImpl.init() populates the algorithms map once when the class is constructed.

We should consider adding a new method to PipelineServinceImpl to recreate the algorithms map when the user updates the system property values (making proper use of locks / synchronization to make sure that nothing is using the map while it is being refreshed). Consider separating-out the following the code in PipelineServiceImpl.init() into the new method:

```
            AlgorithmDefinitionCollection algorithms = fromXStream(propertiesUtil.getAlgorithmDefinitions(),
                    AlgorithmDefinitionCollection.class);

            for (AlgorithmDefinition algorithm : algorithms.getAlgorithms()) {
                try {
                    addAlgorithm(algorithm);
                    log.debug("added algorithm {}", algorithm);
                } catch (WfmProcessingException ex) {
                    log.warn("failed to add algorithm {}", algorithm);
                }
            }
```

I believe that the default values of the algorithm properties that show up in the Pipelines 1 and Pipelines 2 UIs are pulled from the algorithms map, so we should perform a test where we set new detection properties through the Properties UI and then make sure that the new values appear in the pipelines UIs (without restarting the WFM).

**Comment by brosenberg42** [comment]
> We should consider adding a new method to PipelineServinceImpl to recreate the algorithms map

I don't think this is necessary. I think we can just update the algorithms in place.

I think we can change PipelineServiceImpl from:
```
    private void addAlgorithm(AlgorithmDefinition algorithm) {
        algorithm.getProvidesCollection().getAlgorithmProperties()
                .stream()
                .filter(pd -> pd.getPropertiesKey() != null)
                .forEach(pd -> pd.setDefaultValue(propertiesUtil.lookup(pd.getPropertiesKey())));

        validateAlgorithm(algorithm);
        log.debug("{}: Adding algorithm", StringUtils.upperCase(algorithm.getName()));
        algorithms.put(StringUtils.upperCase(algorithm.getName()), algorithm);
    }
```
to
```
    private void addAlgorithm(AlgorithmDefinition algorithm) {
        setAlgorithmDefaultValues(algorithm);

        validateAlgorithm(algorithm);
        log.debug("{}: Adding algorithm", StringUtils.upperCase(algorithm.getName()));
        algorithms.put(StringUtils.upperCase(algorithm.getName()), algorithm);
    }
    
    
    public void refreshAlgorithmDefaultValues() {
    	algorithms.values().forEach(this::setAlgorithmDefaultValues);
    }
    
    private void setAlgorithmDefaultValues(AlgorithmDefinition algorithm) {
        algorithm.getProvidesCollection().getAlgorithmProperties()
                .stream()
                .filter(pd -> pd.getPropertiesKey() != null)
                .forEach(pd -> pd.setDefaultValue(propertiesUtil.lookup(pd.getPropertiesKey())));
    }
```

**Comment by jrobble** [comment]
Go with @brosenberg42's approach.

**Comment by dpierce17** [comment]
If I change detection.sampling.interval between batch jobs, Is there a way I can tap into activeMQ so I can observe the sampling interval that is being sent to the components?  FYI, the current implementation seems to be working (with some UI changes still needed to be made), but I'd like to be able to verify the property values being sent to the components.

**Comment by dpierce17** [comment]
Just to confirm, if a completed job is re-submitted - then it will be using the latest detection.* system properties (if applicable). It won't be using the detection.* system properties that may have been in place when the job was created.

**Comment by jrobble** [comment]
One way to do this would be to start a long-running job by providing a long video file. Make sure you only have one service running for the detection algorithm that will be used. You will see the pending sub-job messages start to accumulate in the component's input queue. You can then make changes to the detection system properties and start another job that uses the same algorithm. Those messages will appear in the component's input queue behind the other ones.

The theory behind this approach is that the long-running job will give you enough time to check the messages in the queue before they are processed.

Alternatively, you could add some debug lines to the component executors to print out the job properties map. Actually, for the Java component executor, you may just need to change [this line](https://github.com/openmpf/openmpf/blob/develop/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java#L71) to `LOG.info()`. Note that the only algorithm that uses the Java component executor is Sphinx. You may want to add some debug lines in [this function](https://github.com/openmpf/openmpf/blob/develop/trunk/detection/executor/cpp/batch/MPFDetectionBuffer.cpp#L72) for the C++ component executor.

**Comment by dpierce17** [comment]
Earlier comments described breaking up the Properties UI into 2 sections, with one section labeled as "Default Job Properties" and the other section called "General System Properties". Would the detection (i.e. mutable) properties be in the "Default Job Properties" section, or visa-versa?

**Comment by dpierce17** [comment]
If we have that mutable system properties section called "Default Job Properties", would it be introducing confusion to be calling these "system" properties "job" properties?  Would they get confused with job properties as they are referred to on the job creation API?

**Comment by jrobble** [comment]
>  would it be introducing confusion to be calling these "system" properties "job" properties?

Yeah, you bring up a good point. How about we call them "Default Detection Properties"?
