### ISSUE TITLE
Investigate automatically registering child node with master node

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#235]
There is some interest in installing OpenMPF in a Docker container. Specifically, there may be containers for master nodes and containers for child nodes.

Determine how a child node registers with the master node. This seems to be related to jgroups. How could we automate / simplify that process so that a pre-existing child node can be associated with a pre-existing cluster of nodes without needing to re-run the deployment scripts to setup the child node?

Just how much work do the deployment scripts do to link the child node with the master node?

**Comment by brosenberg42** [comment]
I was able to take a node originally configured as part of cluster A, and make it part of cluster B.
All I had to do was change how the ALL_MPF_NODES was being set in /etc/profile.d/mpf.sh. 
On Cluster B's master node I added "NewNodeHostname[7800]" to the end of the ALL_MPF_NODES environment variable. On the node I was adding to the cluster, I set ALL_MPF_NODES to be the same as the value in Cluster B's master node.

**Comment by jrobble** [comment]
> I think that’s the problem: The child node has no way to inform the master node what components it has. The master just assumes all of the children are the same. This has implications on the Component Registration page too. We may want to represent each node separately if we’re going to be supporting nodes with different components.

**Comment by jrobble** [comment]
That might be fine if users are aware that all child must match the other children in the cluster, or there will be problems.

**Comment by jrobble** [comment]
Also, component registration and removal through Ansible will only work if the host is added to /etc/ansible/hosts.

**Comment by jrobble** [comment]
The new node has to be added through the Nodes page of the web UI, or through the REST endpoint: [POST] /rest/nodes/config. Both approaches should result in updating nodeManagerConfig.xml.

**Comment by jrobble** [comment]
The child node should be using the same shared network location as the other nodes in the cluster. Specifically, $MPF_HOME/share should point to the same place for all of the nodes in the cluster.
