### ISSUE TITLE
Get Jenkins working with GitHub repos T2438

### ISSUE THREAD

**Issue by Angrymute** [openmpf/openmpf#24]
Get Jenkins builds working with the GitHub repos. We need to update the following builds:

mpf-master
mpf-develop
mpf-phabricator
mpf-nightly
mpf-stress
It may be best to create duplicates of those repos for testing purposes first.

**Comment by brosenberg42** [comment]
mpf-master - This won't work until we merge with develop
mpf-develop - This is now mpf-develop. 
mpf-phabricator - This is now openmpf-github-with-pull-request
mpf-nightly - This now opempf-nightly. It is failing for the same reason that mpf-nightly is currently failing.
mpf-stress - This hasn't been passing in a while.

@jrobble What are we doing about mpf-nightly and mpf-stress?

**Comment by jrobble** [comment]
Do you mean "mpf-develop" is now "openmpf-develop"? 

openmpf-nightly will fail until #28 is resolved.

We haven't had time to address mpf-stress. openmpf-nightly is the first priority. Let's tackle mpf-stress once #28 is resolved. @dpierce17 is working on that.

**Comment by brosenberg42** [comment]
> Do you mean "mpf-develop" is now "openmpf-develop"?

Yea
