### ISSUE TITLE
Investigate why feed-forward is slower than non-feed-forward batch processing

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#247]
Results of some initial tests on a chokepoint video using a MOG MOTION --> OCV FACE pipeline:

> FF w/ tracking: 3:14
> No FF w/tracking: 3:06
> FF no tracking: 1:22
> No FF no tracking: 1:15

Instrument the code to log some execution times:

- Start by logging the time spent in the component executor after parsing the request protobuf and before generating the response protobuf.

- Also, log the time it takes to generate the sub-job request messages in the WFM.

**Comment by brosenberg42** [comment]
Below is a table showing some information I collected. Msgs is the number of messages that get sent to OcvFace. Frames is the number of frames OcvFace will process. I included the pixel count since the feed forward jobs should have to process fewer pixels.

Job Type                | Msgs  | Frames | Pixels
-------------------|-------|--------|---------
FF w/tracking         | 331      | 1,962  | 292,546,368
No FF w/tracking   |  7         | 1,965  | 943,200,000
FF no tracking        | 1,850  | 1,850  | 130,618,688
No FF no tracking  | 6         | 771      | 370,080,000 

The feed forward cases do have less pixels to process, but there are way more messages.

**Comment by jrobble** [comment]
Here are my results:

Job Type                 | Time
-------------------|-------
FF w/tracking         | 6:16
No FF w/tracking   | 3:33
FF no tracking        | 6:07
No FF no tracking  | 2:50

**Comment by brosenberg42** [comment]
@jrobble I ran the tests you asked for.
All the tests were run without markup and USE_PREPROCESSOR=false.

When FF is checked OcvFace gets FEED_FORWARD_TYPE=SUPERSET_REGION.
When Track is checked MoG gets USE_MOTION_TRACKING=1.
When Merge is checked both MoG and OcvFace get MERGE_TRACKS=true.
Time is in seconds
Avg Msg Size is in bytes

FF | Track | Merge | Time | Messages | Avg Msg Size | Frames | Pixels
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | 75 | 718 | 996 | 731 | 350,880,000
  |   | x | 47 | 63 | 1003 | 731 | 350,880,000
  | x |   | 187 | 7 | 995 | 738 | 354,240,000
  | x | x | 187 | 6 | 1002 | 738 | 354,240,000
x |   |   | 72 | 1850 | 1051 | 1850 | 130,618,688
x |   | x | 42 | 632 | 1103 | 1850 | 169,934,912
x | x |   | 195 | 330 | 1164 | 1962 | 292,511,360
x | x | x | 191 | 328 | 1173 | 1961 | 294,656,704

**Comment by jrobble** [comment]
@brosenberg42, looking at these results, merge seems to help when it can reduce the number of messages. Merging seems to speed things up more than turning on FF. Let's run some tests with higher resolution video. Please post the resolution of the video we tested with here.

**Comment by brosenberg42** [comment]
This is what I have so far. I will collect the other stats tomorrow.

Video Resolution: 3840x2160

FF | Track | Merge | Time
-- | -- | -- | --
  |   |   | 740
  |   | x | 238
  | x |   | 342
  | x | x | 344
x |   |   | 582
x |   | x | 176
x | x |   | 281
x | x | x | 275

**Comment by brosenberg42** [comment]
Video Resolution: 3840x2160

FF | Track | Merge | Time | Messages | Avg Msg Size | Frames | Pixels
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | 740 | 247 | 985 | 247 | 2,048,716,800
  |   | x | 238 | 24 | 998 | 247 | 2,048,716,800
  | x |   | 342 | 7 | 985 | 247 | 2,048,716,800
  | x | x | 344 | 7 | 998 | 247 | 2,048,716,800
x |   |   | 582 | 332 | 1039 | 332 | 360,745,472
x |   | x | 176 | 67 | 1165 | 332 | 530,745,344
x | x |   | 281 | 40 | 1216 | 341 | 614,129,152
x | x | x | 275 | 40 | 1249 | 341 | 591,617,536

**Comment by brosenberg42** [comment]
I re-ran the tests on the 800x600 video with artifact extraction disabled

FF | Track | Merge | Time | Messages | Avg Msg Size | Frames | Pixels
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | 60 | 718 | 996 | 731 | 350,880,000
  |   | x | 44 | 63 | 1003 | 731 | 350,880,000
  | x |   | 189 | 7 | 995 | 738 | 354,240,000
  | x | x | 183 | 6 | 1002 | 738 | 354,240,000
x |   |   | 62 | 1,850 | 1051 | 1850 | 130,618,688
x |   | x | 39 | 632 | 1103 | 1850 | 169,934,912
x | x |   | 185 | 330 | 1164 | 1962 | 292,511,360
x | x | x | 187 | 328 | 1173 | 1961 | 294,656,704

**Comment by jrobble** [comment]
Hmm, disabling artifact extraction doesn't look like it did much, if anything. The differences could be attributed to noise. What do you think?

**Comment by brosenberg42** [comment]
> Those differences could be attributed to noise.

Yes, I agree. The running time is also highly dependent on the content of the video and the algorithms used. We will never make it so feed forward is always faster.
