### ISSUE TITLE
Update version numbers in descriptor files

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#264]
Update the "componentVersion" in all the component descriptor files to 1.0.0 and the "middlewareVersion" to 1.0.0 as well.

**Comment by dpierce17** [comment]
Found 0.10.0 references in node manager script .sh files, pom files and the JsonDescriptor component test, so revision of these files were required as well.  Note that changes to descriptor files were required in other repos, and are included as part of this task.
