### ISSUE TITLE
Generate REST API doc from Swagger for getting list of all streaming video jobs and new activity alerts

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#296]
Will land #113.

Generate the REST API doc from Swagger to include endpoint for getting list of all streaming video jobs.

Also, update the following sections for the new activity alert changes:

1.20. HealthReportData
- activity frame id
- activity timestamp 

1.17. StreamingJobInfo
- activity frame id
- activity timestamp 

1.15. StreamingJobCreationRequest
- remove newTrackAlertCallbackUri

2.20 POST /rest/streaming/jobs
- remove newTrackAlertCallbackUri

**Comment by dpierce17** [comment]
Sent first proposal for the REST API doc that contains the endpoint for getting the list of all streaming jobs to jrobble on 11/8/17

**Comment by dpierce17** [comment]
included in Differential Review D2338.

**Comment by dpierce17** [comment]
Landed with D2338
