### ISSUE TITLE
Add healthReportCallbackRate and stallAlertDetectionThreshold system properties

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#297]
Related to #226.

We've decided to add system properties for healthReportCallbackRate and stallAlertDetectionThreshold. 

We no longer require a stallAlertRate system property. 

This is an example of the how a third party system is notified of status changes (via heath report callbacks):

IN_PROGRESS, IN_PROGRESS, IN_PROGRESS, …, STALLED, STALLED, STALLED, …, IN_PROGRESS, IN_PROGRESS, IN_PROGRESS, …, CANCELLED

Note that in the above example the first time the status changes to IN_PROGRESS, STALLED, or CANCELLED, the status is sent out to the third party system immediately (event-based callback). 

If the job is not CANCELLED or TERMINATED, then after the healthReportCallbackRate period elapses the same status is resent.

Note that the health status report is encapsulated in a `HealthReportData` structure which contains the following fields:

- `jobId`: array jobId of the streaming job providing this health report.
- `reportDate`: string The date of this health report.
- `jobStatus`: string A string that will be one of the following values: INITIALIZED | IN_PROGRESS | CANCELLED | TERMINATED | STALLED.
- `externalId`: string External id

**Comment by dpierce17** [comment]
Will define streaming job properties as mpf.job.streaming.healthReportCallbackRate and mpf.job.streaming.stallAlertDetectionThreshold.  Will set healthReportCallbackRate and stallAlertDetectionThreshold defaults to 120 seconds

**Comment by jrobble** [comment]
The convention is to use a period between words. Let's use: `streaming.healthReport.callbackRate` and `streaming.stallAlert.detectionThreshold`. Let's use a default of 30 seconds for both.

**Comment by dpierce17** [comment]
landed with PR380
