### ISSUE TITLE
[openmpf/openmpf-cpp-component-sdk] MPF::COMPONENT::Utils::expandFileName() does not call wordfree()

### ISSUE THREAD

**Issue by clnowacki** [openmpf/openmpf#299]
This function neglects to call wordfree() so the internal allocation leaks memory.

**Comment by clnowacki** [comment]
Closed after merging pull request #45.

**Comment by jrobble** [comment]
Please update the openmpf-cpp-component-sdk SHA in the openmpf-projects repo.

**Comment by clnowacki** [comment]
Done. Thanks for the reminder!
