### ISSUE TITLE
Handle when streaming job cleanup fails

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#320]
Refer to [this TODO](https://github.com/openmpf/openmpf/blob/develop/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L354).

How would the cleanup fail? If the directory doesn’t exist, that’s still a success. If a file is in use and can’t be deleted, set the status and return a meaningful error message in StreamingJobCancelResponse.mpfResponse.

**Comment by dpierce17** [comment]
Part of pull request #331

**Comment by dpierce17** [comment]
landed on 12/1/17 as part of PR #331
