### ISSUE TITLE
Add ARTIFACT_EXTRACTION_POLICY to all descriptor.json files

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#344]
Add ARTIFACT_EXTRACTION_POLICY to all descriptor.json files. This property is supported in the WFM, so by default all components that support videos and images support it.

The default value is determined by the detection.artifact.extraction.policy system property. The valid values are specified in ArtifactExtractionPolicy.java.

This is related to #511. Whatever properties we decide on for that issue must be specified in each component's descriptor file.

**Comment by clnowacki** [comment]
Should this issue be closed in favor of #866?

**Comment by jrobble** [comment]
I think we should leave it open and close it at the same time. It is possible to complete this task without completing #866 if for some reason we don't complete that task.

**Comment by clnowacki** [comment]
866 was completed and is in testing.
