### ISSUE TITLE
Update JSON timestamps to use ISO-8601 formatted timestamps

### ISSUE THREAD

**Issue by dpierce17** [openmpf/openmpf#353]
Timestamps that are generated in OpenMPF are generally of the format "2017-11-06 14:44:26.0".  This timestamp is an example created in WFM using java.util.Date. This timestamp should be considered to be in the timezone currently configured on the system running OpenMPF.  

There is no indication as to what timezone is applicable. Switching to the ISO-8601 format (i.e. looks like: 2011-12-03T10:15:30Z) would make it possible to compare timestamps generated between systems in different time zones. This enhancement would be useful if OpenMPF is ever revised to use timestamps from a remote device.

**Comment by jrobble** [comment]
A better convention may be to UTC timestamps.
