### ISSUE TITLE
Create HealthReport Callback system test

### ISSUE THREAD

**Issue by dpierce17** [openmpf/openmpf#354]
Use Spark to test the Health Report callbacks, by adding a health report test to ITWebREST.java.

**Comment by dpierce17** [comment]
While testing catching of the Health Report POST callback, I'm getting an error from jackson that I want to report on.  The HealthReport is using Java8 time packages (i.e. java.time and java.time.format). I found mention that usage of Java8 java.time with jackson an extension called JavaTimeModule should be used.  That is not quite working,  I'm having trouble parsing a LocalDateTime using the pattern we decided on.  This might have something to do with the older version of jackson-core we are using (i.e. 2.6.1).  When I upped the version to 2.6.7, that didn't help.  When I upped the version to current version (i.e. 2.9.2) the ITWebRest system test wouldn't run, so that's not an immediate option.  My question is, do you know if there is some version of jackson between 2.6.7 and 2.9.2 that you know we can run with, that would be worth trying out?  

To follow-up on this a bit more, if we can't use a later release of jackson-core, I'm going to try writing a custom deserializer for java.time.LocalDateTime.  I'm just logging that fact here.

If you want more painful details on the errors I was getting, see below.

The first time I tested the Health Report POST callback, I got an error from jackson  that looked like this:
*.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.time.LocalDateTime] from String value
Tracking this error down, I saw mention that there is a Jackson java.time extension Module (i.e. JavaTimeModule) that can be used - we just need to use jackson version later than 2.6, and also register the JavaTimeModule in the jackson objectMapper (i.e. objectMapper.registerModule(new JavaTimeModule());).  Since we are using jackson 2.6.1, this looked like the correct approach - so I implemented this, but using jackson 2.6.1 (and also upgraded to 2.6.7) I'm now getting this error:
com.fasterxml.jackson.databind.JsonMappingException: Text '2017-12-07 15:54:38.3' could not be parsed at index 10, which was caused by a java.time.format.DateTimeParseException: Text '2017-12-07 15:54:38.3'.   So, it looks to me like the deserializer in jackson isn't available for the pattern we are using.

**Comment by jrobble** [comment]
> When I upped the version to current version (i.e. 2.9.2) the ITWebRest system test wouldn't run

What was the problem?

**Comment by dpierce17** [comment]
Sorry, I should have included that.  I added Jackson Datatype: JSR310 » 2.9.2 to the WFM pom as described at https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.9.2

Once done, when I ran the ITWebTest system test, I got a HTTP code 500 (general Internal Server Error) as shown at the end of this dialog.  The error is thrown during the legacy tests - which lead me to think that something else was obsoleted by the version update.  I did find a NoSuchMethod error from com.fasterxml.jackson.dataformat.smile in the tomcat logs that gave me more information:

nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.smile.SmileGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;] with root cause

Looking further, I found in the pom that we had defined com.fasterxml.jackson.dataformat.jackson-dataformat-smile.version as 2.5.0.  I updated that version to 2.9.2, and now the legacy tests pass.  I'm still getting the DateTimeParseException exception shown below though, so I'm going to keep working on that.

java.time.format.DateTimeParseException: Text '2017-12-08 10:13:31.3' could not be parsed at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:82)


--------------------------------------------------------------------------------------

Original error when just jackson-core version was updated to 2.9.2 (but com.fasterxml.jackson.dataformat.jackson-dataformat-smile.version was still at version 2.5.0)

[main] INFO org.mitre.mpf.wfm.ui.Utils - TOMCAT_BASE_URL Environment Variable NOT SET and BASE_URL: http://localhost:8080
[main] INFO org.mitre.mpf.wfm.ITWebREST - Starting the REST Tests
[main] INFO org.mitre.mpf.wfm.ITWebREST - Creating new Job
[main] INFO org.mitre.mpf.wfm.ITWebREST - Post to: http://localhost:8080/workflow-manager/rest/jobs Params: {"pipelineName":"OCV FACE DETECTION PIPELINE","externalId":"external id","priority":9,"buildOutput":true,"mediaUris":{"http://localhost:8080/workflow-manager/resources/img/blue-cybernetic-background.jpg":{}}}
[main] ERROR org.mitre.mpf.wfm.ITWebREST - PostJSON Error: Failed to make HttpURLConnection, responseCode is 500, response message is Internal Server Error
[main] INFO org.mitre.mpf.wfm.ITWebREST - Finished REST Tests

java.lang.RuntimeException: Failed : HTTP error code : 500

	at org.mitre.mpf.wfm.ITWebREST.PostJSON(ITWebREST.java:1022)
	at org.mitre.mpf.wfm.ITWebREST.createNewJob(ITWebREST.java:1126)
	at org.mitre.mpf.wfm.ITWebREST.setup(ITWebREST.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Test ignored.

Test ignored.

Test ignored.

Test ignored.

Test ignored.

**Comment by jrobble** [comment]
Ok. Glad you figured out the version issue between jackson-core and jackson-dataformat-smile. My preference would be to upgrade to the latest and greatest if we can.

In order to help more, I will need to see your code. Off hand, you may need to create a [`DateTimeFormatter`](https://www.mkyong.com/java8/java-8-how-to-convert-string-to-localdate/).

**Comment by dpierce17** [comment]
I did create a DateTimeFormatter, I'm just having trouble getting jackson to find it.  I've added @JsonSetter("reportDate") and @jsonGetter("reportDate").  But that didn't help.  I'm seeing mention on the web of other users having issues with jackson not being able to resolve custom LocalDateTime patterns.

**Comment by jrobble** [comment]
Is the code causing you problems pushed to a branch that I could try to debug?

**Comment by dpierce17** [comment]
Since the system tests include creation of 2 streaming jobs (one GET, and one POST) the system test has to include cancellation of the streaming jobs, so that the periodic streaming job health reports will stop.  Adding streaming job cancellation to this system test.

**Comment by dpierce17** [comment]
After last merge with develop - Health Report System test needed to be revised to work with a Mock streaming component.  Jeff now working this issue.

**Comment by dpierce17** [comment]
landed with PR380
