### ISSUE TITLE
Update Swagger [GET] /rest/jobs/{id} date format

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#355]
Related to #353.

In Swagger, [GET] /rest/jobs/{id} shows the following for the Response Class Model Schema:

```
{
  "endDate": "2017-11-28T21:20:47.501Z",
  "jobId": 0,
  "jobPriority": 0,
  "jobProgress": 0,
  "jobStatus": "string",
  "outputObjectPath": "string",
  "pipelineName": "string",
  "startDate": "2017-11-28T21:20:47.501Z",
  "terminal": true
}
```

Here’s what’s actually returned:

```
{
  "jobId": 5,
  "pipelineName": "OCV FACE DETECTION (WITH AUTO-ORIENTATION AND MARKUP) PIPELINE",
  "jobPriority": 4,
  "jobStatus": "COMPLETE",
  "jobProgress": 0,
  "startDate": 1501254026000,
  "endDate": 1501254049000,
  "outputObjectPath": "/home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/5/detection.json",
  "terminal": true
}
```

First, notice that the Model Schema shows UTC time. We’re not actually using UTC time.

Second, notice that the actual date strings returned are not in the specified format. This may be related to the automatic conversion of the `SingleJobInfo` class to JSON in `JobController.getJobStatusRest()`.

<br>
This issue was resolved in [GET] /rest/streaming/jobs/{id} by updating the fields in `StreamingJobInfo` with the `@ApiModelProperty` annotation. For example:

```
@ApiModelProperty(position=2, required = true, dataType="String", value = "streaming job start time, local system time. Example: 2018-01-07 10:23:04.6.")

```

We should do the same to the fields in the `SingleJobInfo` class.

**Comment by brosenberg42** [comment]
Did it actually return 1501254026000 for the timestamp, or did you make it up for this example? If that is what it actually returned, then there is another bug. 1501254026000 is 11/06/49542 @ 7:13am (UTC). If you drop the trailing zeros you get 1501254026 which is 07/28/2017 @ 3:00pm (UTC)

**Comment by jrobble** [comment]
Yes, it did. It's been a long time since I flushed mySQL, so I believe the timestamp is accurate. Here's what it shows:

```
mysql> select id, time_completed, time_received from job_request where id=5;
+----+---------------------+---------------------+
| id | time_completed      | time_received       |
+----+---------------------+---------------------+
|  5 | 2017-07-28 11:00:49 | 2017-07-28 11:00:26 |
+----+---------------------+---------------------+
1 row in set (0.00 sec)
```

I'm up to job id 279 now.

This shows the correct conversion:

```
[mpf@localhost bin]$ date -d @1501254026
Fri Jul 28 11:00:26 EDT 2017
```

**Comment by jrobble** [comment]
The difference is seconds vs. milliseconds. It's possible that the JSON conversion uses milliseconds to try to preserve the maximum precision. The date command above takes seconds.

According to forums, Spring uses Jackson and Jackson serializes to milliseconds: http://www.baeldung.com/jackson-serialize-dates

**Comment by brosenberg42** [comment]
> This issue was resolved in [GET] /rest/streaming/jobs/{id} by updating the fields in `StreamingJobInfo` with the `@ApiModelProperty` annotation.

That doesn't show up as a timestamp it shows up "startDate": "string". I spent some time looking in to setting the format that shows up for the time fields, but there does not appear to be a way to do so in the version of Swagger we are using. Having it say "string" is better than showing the wrong time format, but it would be better if we could change it show an accurate date format.
