### ISSUE TITLE
Upgrade to cmake3 T2153

### ISSUE THREAD

**Issue by Angrymute** [openmpf/openmpf#36]
~~The new C++ components must be built with cmake3.~~ We need to update the build env. setup ~~guide and~~ script to yum install cmake3. Currently cmake 2.8.12.2 is built from scratch.

~~cmake3 must be installed on the Jenkins VMs.~~

The MPF trunk pom must be updated to work with cmake3. It currently does:

<execution>
    <id>cmake-generate-sources</id>
    <phase>generate-sources</phase>
    <goals>
        <goal>exec</goal>
    </goals>
    <configuration>
        <executable>/usr/local/bin/cmake</executable>
        <arguments>
            <argument>-DCMAKE_RULE_MESSAGES=OFF</argument>
            <argument>-DCMAKE_VERBOSE_MAKEFILE=OFF</argument>
            <argument>-DBUILD_SHARED_LIBS=ON</argument>
            <argument>-DCMAKE_BUILD_TYPE=Release</argument>
            <argument>-DCMAKE_INSTALL_PREFIX=../install</argument>
            <argument>../</argument>
        </arguments>
        <successCodes>
            <successCode>0</successCode>
            <successCode>1</successCode>
        </successCodes>
        <workingDirectory>build</workingDirectory>
    </configuration>
</execution>

**Comment by clnowacki** [comment]
This is done.
