### ISSUE TITLE
Check validity of batch job

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#397]
Update `JobController.createJobInternal()` to use `pipelineService.pipelineSupportsBatch()`. This is similar to how `StreamingJobController.createStreamingJobInternal()` does `!pipelineService.pipelineSupportsStreaming(streamingJobCreationRequest.getPipelineName()`. 

It's possible that someone may develop a component that only supports streaming. Using it to create a batch job will cause problems.

**Comment by dpierce17** [comment]
Landed with PR#433
