### ISSUE TITLE
Create StreamingJobStatus class

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#400]
Create a StreamingJobStatus class that's similar to the existing JobStatus class, but is only for stream processing. The enum entries in the class should be limited to those that are only useful for streaming. The TERMINATED, PAUSED, and STALLED entries can be removed from the JobStatus class since they are not relevant to batch processing.

Add a detail (String) field to StreamingJobStatus so that the ERROR status can have additional information. When health reports are generated, they should get the status value from this field if it's populated. Part of this task is to ensure the StreamingJobStatus information can be stored in mySQL and Redis. This is slightly different from storing the JobStatus information because of this additional field.

Also, ensure that the proper StreamingJobStatus is created in `NodeManagerStatus.streamingJobExited()`.

When the WFM receives the segment summary report, if the error string is populated, set the StreamingJobStatus to ERROR, set the detail to that string’s value, and update mySQL and Redis accordingly.

**Comment by dpierce17** [comment]
Where I find deeper links into the legacy code (i.e. AtmosphereController.broadcast) I plan to just send the string equivalent of the streaming job status without the detail field.

**Comment by dpierce17** [comment]
if the stream status detail string is to be added to the persistent storage (mysql), need to alter the mpf streaming_job_request table (for existing jobs) by doing the following:

 mysql --user=root -p -e "alter table mpf.streaming_job_request add column status_detail varchar(255) after status;"

Some variant of this statement will have to be added to the deployment scripts (TODO)

**Comment by dpierce17** [comment]
we should add the mysql alter table statement to mysql.yml. I'll create an issue for this once I get closer to landing this issue

**Comment by dpierce17** [comment]
FYI: I've run into a problem adapting the WFM Hibernate*Dao software (supports persistent storage to mysql database) for StreamingJobStatus (i.e. now a property constructed from two columns of a mysql table). I changed StreamingJobRequest to construct StreamingJobStatus from two columns using Embedded types, but I'm getting an java.lang.IllegalArgumentException similar to as described in this Hibernate bug report: https://hibernate.atlassian.net/browse/HHH-11537. I'll be working with this a bit longer, but wanted to report this possible issue here.

**Comment by jrobble** [comment]
> FYI: I've run into a problem

If you'd like, I can help you debug if you push your code to a branch I can access.

**Comment by dpierce17** [comment]
Landed with PR#433
