### ISSUE TITLE
Generate REST API doc from Swagger to include new segment summary report format

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#403]
Generate the REST API doc from Swagger to include the new new segment summary report format. Right now, in Section 1.15. StreamingJobCreationRequest, the API says:

> The summary report would contain everything in the JSON output object for batch jobs, including output tracks.

That's incorrect and should be updated.

Also, Section 2.20 POST /rest/streaming/jobs should be updated with an example of the segment summary report JSON in a yellow breakout box.

**Comment by dpierce17** [comment]
I don't have the format of the segment summary report. Can you provide it?

**Comment by jrobble** [comment]
[This comment](https://github.com/openmpf/openmpf/issues/348#issuecomment-357045041) needs to be addressed first:

> ... To account for this, we need to create a JSON representation for the segment summary report in the interop package so that we can return it in the callback.

**Comment by dpierce17** [comment]
Add an example JSON summary report within a yellow box to section 2.21 POST  /rest/streaming/jobs

**Comment by dpierce17** [comment]
Add "externalId" field to the segment summary report, externalId should appear after jobId. This is to accommodate issue #445

**Comment by dpierce17** [comment]
Landed with D2365
