### ISSUE TITLE
Update MPF-REST API from Swagger after StreamingJobInfo update

### ISSUE THREAD

**Issue by dpierce17** [openmpf/openmpf#412]
Followup to openmpf issue #411, update MPF-REST API from Swagger after activity frame id, activity timestamp and streaming job status detail have been added to StreamingJobInfo. Include in this task update HealthReportData for addition of streaming job status detail.

**Comment by jrobble** [comment]
Please update the healthReportCallbackUri description by changing:

> Clients that specify the same healthReportCallbackUri will receive identical health reports POSTed to the healthReportCallbackUri.

to:

> If the same healthReportCallbackUri is specified when creating more than one job, the callback will contain health reports for all the jobs created using using that healthReportCallbackUri.

**Comment by dpierce17** [comment]
Update 1.17. StreamingJobInfo jobStatus for latest values. 
Change: 
  INITIALIZED|IN_PROGRESS|CANCELLED|TERMINATED|STALLED
to 
  INITIALIZING|IN_PROGRESS|CANCELLING|CANCELLED|TERMINATED|STALLED|JOB_CREATION_ERROR|ERROR|CANCELLED_BY_SHUTDOWN

**Comment by dpierce17** [comment]
With regards to this change to the same health report being sent to jobs with the same healthReportCallbackUri, isn't this true only for the periodic health reports?  The health reports that are sent due to status change for a specific job, will only contain health for that job. Isn't that correct?  If so, should we call this out in the REST API?

**Comment by dpierce17** [comment]
Landed with D2365
