### ISSUE TITLE
Upgrade to latest jgroups

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#413]
While running system tests on jenkins we've observed that sometimes child node managers lose connectivity with the master node manager. The jgroups messages the children send are ignored (and/or the children are seen as "rogue" node managers"). Updating to the latest version of jgroups may help with this. Currently, the version is 4.0.9.

Note that some settings will be removed in version 4:

> Jan 19, 2018 12:35:07 PM org.jgroups.stack.Configurator resolveAndAssignField
> WARNING: JGRP000014: BasicTCP.use_send_queues has been deprecated: will be removed in 4.0

We need to determine if those settings are necessary and if removing them will have any negative impact.

**Comment by jrobble** [comment]
Note that there is a known issue on Jenkins that occurs when more than one build is running and each build is using a different version of jGroups. To avoid this, all developers should update to the most recent version of jGroups at the same time so that only builds with the same version are running.

**Comment by brosenberg42** [comment]
When more than one Jenkins build runs with two different versions of JGroups the following error message appears constantly in the logs:
`
SEVERE: JGRP000030: jenkins-3-16083: failed handling incoming message: java.lang.NullPointerException
Jan 22, 2018 5:14:23 PM org.jgroups.protocols.TP$MyHandler run
`
