### ISSUE TITLE
alter the mpf streaming_job_request table to adapt for new parameters added streaming job request

### ISSUE THREAD

**Issue by dpierce17** [openmpf/openmpf#427]
As described in Issue #400, the mpf streaming_job_request table needs to be adapted to work with the changes made to support streaming job status vs. batch job status. i.e. new column named status_detail needs to be added to the table. The command to do this is:

mysql --user=root -p -e "alter table mpf.streaming_job_request add column status_detail varchar(255) after status;"

Some variant of this statement will have to be added to the deployment scripts. This command needs to be run before the WFM is started. Recommended placement is in mysql.yml.

**Comment by dpierce17** [comment]
As described in Issue #440, activity frame id and activity timestamp have been added to StreamingJobRequest. The mpf streaming_job_request table needs to be adapted to support existing jobs.. i.e. new columns named activity_frame_id and activity_timestamp need to be added to the table. The commands to do this are:

mysql --user=root -p -e "alter table mpf.streaming_job_request add column activity_frame_id varchar(255);"
mysql --user=root -p -e "alter table mpf.streaming_job_request add column activity_timestamp datetime;"

**Comment by dpierce17** [comment]
Landed with PR442

**Comment by jrobble** [comment]
Moved to testing until we can do some more deployment tests.

**Comment by dpierce17** [comment]
Transferred this issue to Jeff since he and Brian have been doing this deployment testing.
