### ISSUE TITLE
Add external id to segment summary report

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#445]
Add "externalId" field to the segment summary report, similar to how the health reports have it.

Ensure that the externalId appears after jobId by adding it after "jobId" in this list:

```
@JsonPropertyOrder({ "reportDate", "jobId", "segmentId", "segmentStartFrame", "segmentStopFrame",
        "errorMessage", "detectionType", "tracks" })
```

**Comment by dpierce17** [comment]
Adding to PR441

**Comment by dpierce17** [comment]
Looking at this now, but I'm seeing at least one instance where I'm not finding externalId available to add to the summary report. For example, in StreamingJobRoutesBuilder end point WFM_STREAMING_JOB_SUMMARY_REPORTS I don't see external id as available for usage.  I don't see it in DetectionProtobuf.StreamingDetectionResponse. FYI, I just merged with develop.

**Comment by dpierce17** [comment]
Revising previous comment. This issue will be covered under a separate pull request.

**Comment by dpierce17** [comment]
Landed with PR454
