### ISSUE TITLE
Update [GET] /rest/pipelines to return if each pipeline supports batch and/or stream processing

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#477]
Update [GET] /rest/pipelines to return if each pipeline supports batch and/or stream processing.

**Comment by dpierce17** [comment]
Question: can a pipeline support batch and also support streaming, or is it one or the other?

**Comment by jrobble** [comment]
It can be both. At least one is required.

**Comment by dpierce17** [comment]
Currently, the model for this response is:
[
  string
]
I plan to change this to:
[{ name: "pipelineName", supportsBatch: "trueOrFalse", supportsStreaming: "trueOrFalse" }]
Let me know if this needs to be changed

**Comment by jrobble** [comment]
Looks good to me. Note that you may need to update a few system tests once you make this change.

**Comment by dpierce17** [comment]
There is also /pipelines/{pipelineName} returns PipelineDefinition. Should I include supports batch or streaming here too?

**Comment by jrobble** [comment]
That is not an external endpoint. Since we currently don't have a need to change it's behavior, I don't think we should bother unless it helps you in some way.

**Comment by dpierce17** [comment]
Landed with PR#498
