### ISSUE TITLE
Update REST API doc with an example of the JSON input for [POST] /rest/nodes/config

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#487]
Update REST API doc with an example of the JSON input for [POST] /rest/nodes/config.

**Comment by dpierce17** [comment]
Can [GET] /rest/nodes/config be used to generate the JSON input we are looking for here? For example, [GET] /rest/nodes/config when run on sugarbowl-7-mpfd8 (Env 4) produces a JSON response that can be used as the JSON input example for [POST] /rest/nodes/config. Should I use that or are we looking for something shorter?

**Comment by dpierce17** [comment]
Landed with D2392
