### ISSUE TITLE
Update OpenCV to resolve TIFF rotation issues

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#490]
[This issue](https://github.com/opencv/opencv/issues/10703) was recently resolved. The fix is currently in the OpenCV master branch, which is has the [3.4.0-dev version](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/version.hpp).

**Comment by brosenberg42** [comment]
This is no longer an issue since we now use `cv::VideoCapture` instead of `cv::imread`.
