### ISSUE TITLE
OpenMPF User-Guide create-custom-pipelines: fix wrong menu reference

### ISSUE THREAD

**Issue by dpierce17** [openmpf/openmpf#491]
OpenMPF User-Guide Create Custom Pipelines instructions say to Select "Create Custom Pipelines" from the Workflow Manager menu. A "Create Custom Pipelines" menu item doesn't exist, the name of the menu item to be used is actually "Pipelines" under the Workflow Manager Configuration menu.

**Comment by jrobble** [comment]
Fixed in https://github.com/openmpf/openmpf.github.io/pull/52.
