### ISSUE TITLE
Support a FRAME_RATE_CAP property to adaptively adjust the frame interval

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#493]
Currently, there is a `detection.sampling.interval` system property which is used to set the default value for FRAME_INTERVAL. Otherwise, users can specify the value of FRAME_INTERVAL as job property or pipeline property.

In addition to the `detection.sampling.interval` system property, support a `detection.frame.rate.cap` property that can be used to set a threshold on the maximum number of frames to process within one second of the native video time.

In addition to the system property, support a FRAME_RATE_CAP job / pipeline property.

For example, consider that a video as a native 30 FPS. If FRAME_RATE_CAP = 10, then the computed frame interval will be 3. That will result in processing 10 frames within one second of captured video footage.

If the video had a native 5 FPS, that is less than the FRAME_RATE_CAP of 10, so the computed frame interval will be 1. That will result in processing 5 frames within one second of captured video footage, which are all the frames that are available. 

When FRAME_RATE_CAP and FRAME_INTERVAL are both specified then use FRAME_RATE_CAP. If only one is set when the job is created, or specified as a pipeline property, then that will take precedence over the other (whose default value would otherwise be pulled from a system property).

When neither FRAME_RATE_CAP or FRAME_INTERVAL is specified, check the system properties: `detection.sampling.interval` and `detection.frame.rate.cap`. 
- If they are both set to a positive value, then `detection.frame.rate.cap` takes precedence.
- If only one is set to a positive value, then that one takes precedence.
- If they are both set to a zero or negative value (which should generate a warning since it’s user error), then use a frame interval of 1.

**Comment by jrobble** [comment]
One way to support this will be to have the WFM determine the COMPUTED_FRAME_INTERVAL in the media inspection step after determining the video's native FPS. Both the FPS and COMPUTED_FRAME_INTERVAL can be specified in the media properties map.

**Comment by dpierce17** [comment]
Just to confirm, you are requesting a FRAME_RATE_CAP system property (detection.frame.rate.cap), FRAME_RATE_CAP job property and a FRAME_RATE_CAP pipeline property. What should be the default value for the FRAME_RATE_CAP system property?

**Comment by dpierce17** [comment]
FPS storage seems to be in two places in TransientMedia. I find it as class property fps (with setter and getter methods), and I also find it in metadata HashMap as key FPS. It looks like other classes are setting and getting FPS in/from metadata, and the class property fps is unused. Just an FYI that I'm removing fps as a class property since it isn't being used.

**Comment by jrobble** [comment]
> Just to confirm, you are requesting a FRAME_RATE_CAP system property (detection.frame.rate.cap), FRAME_RATE_CAP job property and a FRAME_RATE_CAP pipeline property. What should be the default value for the FRAME_RATE_CAP system property?

The default value should be -1 (disabled). 

I created wishlist task https://github.com/openmpf/openmpf/issues/500 for later. Technically, it's not necessary to declare a property in a component's descriptor file before it can be used when creating a job, but it is necessary to declare it so that the user can set it when creating custom pipeline.

For this task, you can just set the FRAME_RATE_CAP property in the job properties map in the job creation JSON in Swagger to make sure your WFM logic works.

**Comment by jrobble** [comment]
> Just an FYI that I'm removing fps as a class property since it isn't being used.

I agree. It should be removed since it's not used.

**Comment by dpierce17** [comment]
I see in the MediaInspectionProcessor where TransientMedia FPS is being initialized. If FRAME_RATE_CAP from jobProperties or algorithProperties (i.e. pipeline properties) is to be used in conjunction with TransientMedia FPS to set FRAME_INTERVAL, I need to find some point in the code flow after MediaInspectionProcessor where TransientJob and TransientMedia are both available, and before the job is sent to the Components. I'm having trouble identifying where in the WFM software that might be.  If you look at the schematic on https://openmpf.github.io/docs/site/Workflow-Manager/index.html#job-management, the route to the Components (via protobufs?) isn't shown. Can somebody point me in the right direction?

**Comment by jrobble** [comment]
According to the doc, it seems that the JobRouterRoute generates the sub-job messages that are sent to components. The corresponding class is actually `JobRouterRouteBuilder`, which uses `DefaultStageSplitter`, which uses `DetectionSplitter`. The latter class has a `performSplit` method that is used to generate the final properties sent in the sub-job message.

Note that it gets the TransientMedia from the TransientJob:

```
for (TransientMedia transientMedia : transientJob.getMedia()) {
```

**Comment by dpierce17** [comment]
FYI, the key/value pairs in jobProperties (and algorithm properties) don't seem to be defined in the MPF REST API. For example, we are using -1 to disable FRAME_RATE_CAP but only those-in-the-know would know this fact. At some point, the key/value pairs should be provided in the MPF REST API. Can we add this as a wish list item?

**Comment by jrobble** [comment]
> FYI, the key/value pairs in jobProperties (and algorithm properties) don't seem to be defined in the MPF REST API

This is by design. Each component can accept different properties. They should all be defined in the component's descriptor.json file. When creating a new pipeline for that component, you can see the descriptions in the web UI. Listing all the properties for every component in the REST API would be difficult to manage, and overwhelming. It's assumed that users know that job properties to use because they are familiar with the component.

**Comment by dpierce17** [comment]
FYI, samplingInterval also seems to be used in TrackMergingProcessor. Should FRAME_RATE_CAP also be applied in track merging? (see : String samplingInterval = AggregateJobPropertiesUtil.calculateValue(MpfConstants.MEDIA_SAMPLING_INTERVAL_PROPERTY, ... )

**Comment by jrobble** [comment]
`TrackMergingPlan.getSamplingInterval()` is unused. At one time there were plans to use it, but that didn't happen. For now,. let's not worry about adding the frame rate cap data member to the track merging plan.

**Comment by dpierce17** [comment]
I'm working with media who is whose FPS (according to output-object JSON media.mediaMetaData is 29.97. When computing frame interval, should we round up (i.e. we want whole numbers, correct?)

**Comment by jrobble** [comment]
We should calculate the frame interval so that we error on the side of processing more data, not less. That would mean rounding the frame interval down if it's a decimal number. The goal of the FRAME_RATE_CAP is to ensure that a minimum number of frames are processed per second.

**Comment by dpierce17** [comment]
If after applying the FRAME_RATE_CAP rules, the computed frame interval is determined to be <1 (a possibility since the user may not know the medias FPS) - what is the preference? Currently, DetectionSplitter will throw a WfmProcessingException. Would you rather it do something else?

**Comment by brosenberg42** [comment]
I think the formula we want to use is: 
`frame_interval = max(1, floor(actual_fps / cap))`

We probably want to use floating point division rather than integer division, so the Java code would look like:
```
double actualFps = getFps();
double frameRateCap = getCap();
int computedFrameInterval = Math.max(1, (int) (actualFps / fpsCap));
```

Just FYI 29.97 fps is the standard frame rate for NTSC

**Comment by brosenberg42** [comment]
> If after applying the FRAME_RATE_CAP rules, the computed frame interval is determined to be <1 (a possibility since the user may not know the medias FPS) - what is the preference?

This is not an error, so you should not throw an exception. If the computed frame interval is less than one, then that means that the video's frame rate is already lower than the cap. This means all the frames should be processed, so the computed frame interval should be 1.

**Comment by brosenberg42** [comment]
> If the computed frame interval is less than one

Actually this will never happen if you use the formula I gave you: 
`frame_interval = max(1, floor(actual_fps / cap))`

The `floor(actual_fps / cap))` part can end up being 0, but `max(1, 0) = 1`.

**Comment by dpierce17** [comment]
I have a question about precedence for algorithm properties, if you are running a pipeline that contains 2 actions - how to handle override of FRAME_RATE_CAP job property?  Since there is only a single mediaProperties - but may be more than 1 set of algorithm properties (one for each action), if the FRAME_INTERVAL is defined in at least one of the algorithm properties - should that override the FRAME_RATE_CAP job property?

**Comment by jrobble** [comment]
You bring up a good point. We didn't think of it before. Currently, each stage (action) of the pipeline can support a different FRAME_INTERVAL. In theory, it could also support a different FRAME_RATE_CAP. To be consistent, each stage should be able to support a different COMPUTED_FRAME_INTERVAL. 

Looking the the JSON output object, there is one media properties map for each piece of media. Changing the contents of that map for each stage does not seem like the right thing to do. That said, let's calculate COMPUTED_FRAME_INTERVAL for each stage and pass it in the job properties map.

**Comment by dpierce17** [comment]
There is only one jobProperties - just as there is only one mediaProperties - so I'm not clear on how that should be handled. Wouldn't it be better to put COMPUTED_FRAME_INTERVAL for each stage in algorithm properties?

**Comment by jrobble** [comment]
There is only one job properties map in the JSON output object, that's true; however, each sub-job message sent to the component queues can contain different job properties. The entries in that map are determined based on the user-specified job properties, algorithm properties, and pipeline properties. Refer to `DetectionSplitter.performSplit()`.

The final version of the job properties map in each of those messages is not directly reflected in the final JSON output object, rather, that information is indirectly captured by listing the user-specified job properties, algorithm properties, and pipeline properties in the JSON. This is by design.

I think that, technically, each sub-job message can also contain a different media properties map; however, after reviewing how `DetectionSplitter.performSplit()`makes use of `transientMedia`, that seems like it will be a bit difficult to implement. 

My initial concern was that if we put the COMPUTED_FRAME_INTERVAL in the media properties map it would not show up in the JSON output object. Now that I think about it more, that doesn't matter. Making it a job property won't change that. That's not really an issue. Moving forward, the reason I think we should put it in the job properties map is because of the aforementioned difficulty with changing the media metadata in `transientMedia` for every sub-job.

**Comment by jrobble** [comment]
> aforementioned difficulty with changing the media metadata in transientMedia for every sub-job

There are ways around this, but I don't think it's worth our time right now.

**Comment by jrobble** [comment]
> Wouldn't it be better to put COMPUTED_FRAME_INTERVAL for each stage in algorithm properties?

I think we're on the same page here if what you're referring to is `algorithmProperties` in this code:

```
				// get detection request messages from ActiveMQ
				DetectionContext detectionContext = new DetectionContext(
						transientJob.getId(),
						transientJob.getCurrentStage(),
						transientStage.getName(),
						actionIndex,
						transientAction.getName(),
						isFirstDetectionStage,
						algorithmProperties,
						previousTracks,
						segmentingPlan);
```

It's a little confusing because I would call that final properties map the job properties map; however, in the code it's referred to as algorithm properties - possibly due to historical reasons. What I would call algorithm properties is actually `transientJob.getOverriddenAlgorithmProperties()`.

**Comment by dpierce17** [comment]
It looks like the all properties are being sent to the Components via the DetectionContext algorithmProperties. In one example I'm testing with (i.e. setting FRAME_INTERVAL and FRAME_RATE_CAP as jobProperties - FRAME_RATE_CAP should take precedence) , I'm testing with a pipeline that has two actions - so 2 DetectionContexts are being created (one for each action). The DetectionSplitter is consolidating all of the properties (system,job,algorithm) into the algorithmProperties in the DetectionContext constructor. I currently have addition of COMPUTED_FRAME_INTERVAL property to algorithmProperties working (so, this property is now in the DetectionContext) . Does this describe the behavior we are looking for? Note that I'm not removing FRAME_INTERVAL from the DetectionContext - so all properties (FRAME_INTERVAL, COMPUTED_FRAME_INTERVAL and FRAME_RATE_CAP) will be sent to the Components (that's how it looks to me anyway, I can't view that traffic). Is this the correct behavior for this example? Or, should I remove FRAME_INTERVAL from the DetectionContext?

**Comment by dpierce17** [comment]
In a second example I'm testing with (sets JobProperty FRAME_INTERVAL, and FRAME_RATE_CAP as an algorithm property for one action in the 2 action pipeline - FRAME_RATE_CAP should take precedence only for that specific algorithm). In this example, I have addition of COMPUTED_FRAME_INTERVAL property to algorithmProperties for only the single action working (so, this property is now in the DetectionContext for only the algorithm that FRAME_RATE_CAP was defined for in the algorithmProperties job request) .  I think this is the behavior we are looking for as well. Let me know if this isn't the case.

**Comment by jrobble** [comment]
To answer all of your questions, you're current behavior is in line with my current expectations and what we discussed. However, I just talked to @brosenberg42 about his preference. We decided that he only really needs the COMPUTED_FRAME_INTERVAL. That means we never need to pass the FRAME_INTERVAL or FRAME_RATE_CAP in the job properties map. 

In the case where the user only specifies a FRAME_INTERVAL, and not a FRAME_RATE_CAP, then just set COMPUTED_FRAME_INTERVAL = FRAME_INTERVAL and only return the COMPUTED_FRAME_INTERVAL in the map. That way @brosenberg42 only ever needs to look for a COMPUTED_FRAME_INTERVAL entry.

Also, please create a JUnit test class. Both FRAME_INTERVAL and FRAME_RATE_CAP can have 4 possible settings: {algorithm property, job property, pipeline property, system property}. That's a total of 4 x 4 = 16 combinations. Please create a test for each and make sure the value of COMPUTED_FRAME_INTERVAL is what you expect. If you implement some helper methods you shouldn't need to write a lot of code for each individual test case.

Also, FYI, moving forward COMPUTED_FRAME_INTERVAL will always be part of the job properties map for each sub-job. I cannot think of a case where it will not be there. That's because, minimally, the system properties will always be used as backup to generate it.

**Comment by dpierce17** [comment]
Can you clarify the property categories to be tested? I'm familiar with setting system properties via the mpf property file and with setting job properties and/or algorithm properties via the JobCreationRequest. But, I'm not clear on how to set pipeline properties, how should I test this?

**Comment by jrobble** [comment]
I saw this comment above `DetectionSplitter.performSplit`:

```
// property priorities are assigned in this method.  The property priorities are defined as:
// action-property defaults (lowest) -> action-properties -> job-properties -> algorithm-properties -> media-properties (highest)
```

I forget about media properties. That means both FRAME_INTERVAL and FRAME_RATE_CAP can have 5 possible settings: {media property, algorithm property, job property, pipeline property, system property}. That's a total of 5 x 5 = 25 combinations

**Comment by dpierce17** [comment]
Landed with PR506
