### ISSUE TITLE
Make artifact extraction more configurable

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#511]
Currently, the WFM supports the detection.artifact.extraction.policy system property. This can be set to the following values: {NONE, VISUAL_EXEMPLARS_ONLY, EXEMPLARS_ONLY, ALL_VISUAL_DETECTIONS, ALL_DETECTIONS}. Those values are all defined in ArtifactExtractionPolicy enum.

In this context, the properties with "VISUAL" in their name are used to restrict artifact extraction to visual object types. Specifically, anything other than "MOTION" and "SPEECH". Refer to this code in ArtifactExtractionSplitterImpl.java:

```
	private boolean isNonVisualObjectType(String type) {
		return StringUtils.equalsIgnoreCase(type, "MOTION") || StringUtils.equalsIgnoreCase(type, "SPEECH");
	}
```

That code should be updated to include "SCENE". It would be better if the non-visual types were listed in a .properties file instead of hard-coded.

Moving forward, implement support for multiple system properties:

- detection.artifact.extraction.policy = [NONE / VISUAL_ONLY / ALL_FRAMES]
  - If set to VISUAL_ONLY, restricts artifact extraction to object types that aren't MOTION, SPEECH, or SCENE. If artifact extraction is to be performed, use the properties below to determine which frames to extract.
  - If set to NONE or ALL_FRAMES, extract nothing or all frames that are part of each track. respectively. Supersedes the properties below.
- detection.artifact.extraction.policy.exemplar.frame = [TRUE / FALSE]
  - Extracts the exemplar from the track.
- detection.artifact.extraction.policy.first.frame = [TRUE / FALSE]
  - Extracts the first frame from the track.
- detection.artifact.extraction.policy.middle.frame = [TRUE / FALSE]
  - Extracts the middle frame from the track.
- detection.artifact.extraction.policy.last.frame = [TRUE / FALSE]
  - Extracts the last frame from the track.
- detection.artifact.extraction.policy.top.confidence.count = [INT (<= 0 if disabled)]
  - First sorts the detection by confidence value (lower frame number wins if two detections share the same confidence). The top N detections are selected and their frames are extracted.
- detection.artifact.extraction.policy.exemplar.before.after.count = [INT (<= 0 if disabled)]
  - If this is set > 0, then extract the exemplar (supersedes detection.artifact.extraction.policy.exemplar.frame) as well as the N frames before it, and the N frames after it (if they exist, depending on video length). It does not matter if those frames are part of the track.

Note that in some cases enabling more than one of these properties can result in selecting the same frame more than once; for example, if the first frame is also the exemplar. We should probably use a `set` to collect the frames to be extracted in order to prevent duplication.

This is related to #344.

**Comment by brosenberg42** [comment]
For detection.artifact.extraction.policy.middle.frame, which frame would extracted if the track contained detections in the following frames: `[0, 1, 2, 5, 10]`? The middle of the range 0, 10 is 5, but the median is 2.

**Comment by jrobble** [comment]
My thought is that the middle frame is calculated as:

`startFrame + floor((stopFrame - startFrame) / 2)`

And has nothing to do with the actual detections; however, it doesn't really make sense to extract a frame without a detection in it. Maybe the best thing to do is extract a frame with a detection in it that's closest to the middle frame.

For example, following the above calculation, the middle frame is 5. There is a detection at that frame, so that's what you would use. 

However, consider the following frames: `[0, 1, 2, 6, 10]`. Again, the middle frame is 5, but there is no detection there. The closest detection to frame 5 is at frame 6, so that's what we use.

What do you think of this approach? If you're agreeable, we can propose it to the end users.

**Comment by brosenberg42** [comment]
I think you should simplify the expression to `floor((startFrame + stopFrame) / 2)`. That makes it clearer that you are just taking the average.

**Comment by jrobble** [comment]
Ok. I'm fine with that simplification. I will ask about "choosing the frame with a detection which is closest to the middle frame" approach.

**Comment by jrobble** [comment]
Users like "choosing the frame with a detection which is closest to the middle frame" approach. Let's go with that.

**Comment by jrobble** [comment]
Users don't like the idea of having too many system properties. Rather, they asked for a single configuration file with enabled/disabled entries for the various settings. This is kind of what we have in mind:

```
track.extract.first.frame=[true/false]
track.extract.middle.frame=[true/false]
track.extract.last.frame=[true/false]
```

**Comment by clnowacki** [comment]
With just the three artifact extraction policies listed above, the only way that a user could ask for artifact extraction from the non-visual data types would be to use the ALL_FRAMES policy, and there is no way for them to use the newer artifact extraction properties such as first, middle, or last frame in non-visual types.

We need an additional artifact extraction policy, "ALL_TYPES", to provide for artifact extraction for non-visual media types, such as MOTION and SCENE. The VISUAL_ONLY policy will be changed to VISUAL_TYPES_ONLY.

**Comment by clnowacki** [comment]
The following change has been made to the requirements for this issue, per user request.

The detection.artifact.extraction.policy.exemplar.frame and detection.artifact.extraction.policy.exemplar.before.after.count properties have been combined into one property called detection.artifact.extraction.policy.exemplar.frame.plus. The value of the property is an integer N. If N = 0, then only the exemplar frame will be extracted. If N > 0, then N frames before and after the exemplar will be extracted, providing that they fall within the bounds of the track start and stop frame. If N < 0, then this policy is disabled.

**Comment by clnowacki** [comment]
The interaction between these new artifact extraction properties and the existing mpf.output.objects.last.stage.only and mpf.output.objects.exemplars.only properties is defined as follows:
1. If mpf.output.objects.last.stage.only=true, then only extract artifacts for the last stage according to the artifact extraction policy settings.
2. If mpf.output.objects.exemplars.only=true, respect the artifact extraction policy settings and make sure that the output object has a detection entry for every artifact extracted. This means we can extract more than just the exemplar. For example, if the settings to extract the first and last detection are true, then ensure there are detection entries in the output object for the first and last detection. There should also be an entry for the exemplar detection in the output object, but it may or may not have an extraction, depending on the artifact extraction settings.
3. In any case, setting the detection.artifact.extraction.policy property to ALL_DETECTIONS will override the mpf.output.objects.exemplars.only property, and would still extract all detections. However, this may occur only in the last stage if mpf.output.objects.last.stage.only=true.

**Comment by clnowacki** [comment]
Completed with PR 869
