### ISSUE TITLE
Algorithm properties declared in descriptor files that use "propertiesKey" don't interpolate property values.

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#513]
If you don’t set an algorithm property, and it uses “propertiesKey", then it uses the value from the properties file. The value is literally what is in properties file, it doesn’t replace the ${vars}. 

Basically .properties that starts with “detection.” can’t use ${}. Most keys referenced by propertiesKey elements start with “detection."

**Comment by jrobble** [comment]
The user can avoid this issue by providing an absolute path.

This prevents us from setting the value of detection.models.dir.path to "{$MPF_HOME}/share/models/". For the interim, it's hardcoded to "/opt/mpf/share/models/".
