### ISSUE TITLE
Investigate 100% CPU utilization when running Darknet GPU code

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#563]
Our users are noticing 100% CPU utilization when our code is running on their system and using the GPU. We found this [post](https://devtalk.nvidia.com/default/topic/982334/cuda-programming-and-performance/100-cpu-usage-linux/):
 
> "I created a kernel which took 10ms to execute in order to see what is the CPU behavior when a kernel is running on a GPU. Thanks to some topics on this forum I understood that the CPU is spinning to wait the end of a GPU process (default behavior). Thus it's using 100 % of the CPU. I learned that when you are using cudaSetDeviceFlags with the cudaDeviceScheduleBlockingSync flag, the process will be blocked and the CPU could be used for something else. It means that the cpu usage is lower than the spinning mode."
 
It’s a bit surprising that the default CPU behavior is just to sit and spin. We should test with the `cudaDeviceScheduleBlockingSync` flag set to see if it does anything. It's also possible that the Darknet code is calling a function to intentionally sit and spin.

**Comment by clnowacki** [comment]
Testing with the cudaDeviceScheduleBlockingSync flag showed a 25% improvement in CPU utilization.
