### ISSUE TITLE
Add support for MIN_GAP_BETWEEN_TRACKS and MIN_TRACK_LENGTH T1934

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#58]
Most algorithms that support video have a MERGE_TRACKS property that affects the algorithm output. When set to true, the WFM merges generated tracks that are only 1 frame apart. To allow for more fine-grained control, we propose two properties: MIN_GAP_BETWEEN_TRACKS and MIN_TRACK_LENGTH.

- MIN_GAP_BETWEEN_TRACKS will behave similarly to the MIN_GAP_BETWEEN_SEGMENTS property, but will be applied to track outputs rather than segment inputs. Specifically, the WFM will merge a track with the preceding track if the number of frames between them is less than MIN_GAP_BETWEEN_TRACKS.
- MIN_TRACK_LENGTH will behave similarly to the MIN_SEGMENT_LENGTH property. After merging tracks based on MIN_GAP_BETWEEN_TRACKS, the WFM will inspect the length of each track. If it is less than MIN_TRACK_LENGTH then the track will be merged with an adjacent track or dropped.
Thus, you could set the following properties on the motion preprocessor:

MIN_GAP_BETWEEN_TRACKS = 5
MIN_TRACK_LENGTH = 10

This will merge adjacent tracks that are less than 5 frames apart into the same track. If any of those tracks are less than 10 frames in length they will be dropped.

With the addition of those these two properties we can remove MERGE_TRACKS. If track merging is not desired then the default values of MIN_GAP_BETWEEN_TRACKS = 1 and MIN_TRACK_LENGTH = 1 can be used.

To be clear, here’s the flow for a 2-stage motion detection --> face detection pipeline:

- Motion preprocessor stage
  - WFM applies {MIN_GAP_BETWEEN_SEGMENTS, MIN_SEGMENT_LENGTH, TARGET_SEGMENT_LENGTH} properties to source media to generate segments for initial stage
  - Media is segmented and fed into motion detection preprocessor
  - Motion detection preprocessor generates tracks
  - WFM applies {MIN_GAP_BETWEEN_TRACKS, MIN_TRACK_LENGTH} properties and changes the track output
- Face detection stage
  - WFM applies {MIN_GAP_BETWEEN_SEGMENTS, MIN_SEGMENT_LENGTH, TARGET_SEGMENT_LENGTH} properties to generate segments for this stage
  - Media is segmented and fed into face detection algorithm
  - Face detection algorithm generates tracks
  - WFM applies {MIN_GAP_BETWEEN_TRACKS, MIN_TRACK_LENGTH} properties and changes the track output

**Comment by bccole** [comment]
The current flow through the WFM works as follows:

**Comment by bccole** [comment]
Consider the following use case:

A video file is 300 frames, with segment length 100.
Tracks are found spanning:
- 20-40
- 42-55
- 60-62
- 98-99
- 100-102
- 199
- 202

Assume a MIN_TRACK_LENGTH=4,  MIN_GAP_BETWEEN_TRACKS=3.

1. Do 20-40 and 42-55 merge despite the advice of the component?
2. Is 60-62 returned, or pruned out?
3. Is 199-202 returned despite only having two frames?

I am assuming the results would be:
- 20-55
- 98-102
- 199-202

Can we confirm?

**Comment by bccole** [comment]
As a development note -- the main bulk of this work will be done in TrackMergingPlan and TrackMergingProcessor, where the tracks are currently combined and pruned based on the MERGE_TRACKS rules.

**Comment by jrobble** [comment]
To answer your questions:

1. Yes, 20-40 and 42-55 merge since the are 2 frames apart (4 < 2).

2. Track 60-62 is 5 frames from track 42-55 and 36 frames from track 98-99 so it can’t be merged. It’s dropped since its smaller than 4 frames (3 < 4).

3. Track 199-202 is 97 frames from track 100-102 so it can’t be merged. It’s exactly 4 frames so it’s not dropped.

Working through this in two phases:

**MERGE TRACKS RESULTS**

20-55
60-62
98-102
199-202

**DROP TRACKS RESULTS**

20-55
98-102
199-202

So yes, you’re right.
