### ISSUE TITLE
Add tracking to Darknet component

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#592]
Add tracking to Darknet component. Refer to the OCV face detection and Dlib face detection components, among others, to determine how generic tracking is implemented in the rest of OpenMPF. Generally, tracking is performed by checking the amount of bounding-box overlap between two frames.

OpenCV also has various built-in tracking algorithms that would be worth consideration. 

The Darknet component supports a preprocessor mode and default mode of operation. Investigate adding tracking to each, prioritizing the latter.

**Comment by brosenberg42** [comment]
I don't think the OCV trackers will help us. You give it the initial bounding box, then the tracker tells you the bounding box for each subsequent frame. The idea with the OCV trackers is that you only do detection on the first frame, then do tracking on the rest to save processing power.
Step 5 and step 6 in https://docs.opencv.org/3.1.0/d2/d0a/tutorial_introduction_to_tracker.html explain the two tracking methods.
