### ISSUE TITLE
Create an initial set of Dockerfiles

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#597]
Create the following Docker containers, and get them running on a single host machine. Note that the images marked with * can probably be found online and used with minimal modification. The goal is to have a Dockerfile that can generate the image for each container, one Dockerfile per image:

- ActiveMQ container *
- mySQL container * with Docker volume for the database
- Redis container *
- Tomcat container (needs JRE and Python, as well as OpenCV and FFmpeg for media inspection and markup)
   - Connect to a Docker volume that contains the shared network space (i.e. $MPF_HOME/share)
- Container for node-manager and components (needs JRE and Python, as well as FFmpeg)
   - Connect to a Docker volume that contains the shared network space (i.e. $MPF_HOME/share)
   - The Nodes UI and Component Registration UI should still work.

**Comment by bquinn17** [comment]
Completed with https://github.com/openmpf/openmpf-docker/pull/1
