### ISSUE TITLE
Retrieve media from HTTP object storage

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#620]
Process media stored on an object storage server. The media URL will be provided using the HTTP protocol. Currently, when the media URL is specific as HTTP, the WFM will copy of the piece of media to a temporary file in the shared network space. For large files this is inefficient. Also, if the job fails in an unrecoverable way, the large file is left and an administrator must manually clean it up.

Moving forward, all components must declare support for HTTP object storage (true / false) in their descriptor file. Also, add a `detection.copy.file.when.http.not.supported` system property that is used to determine if the WFM should perform a local file copy in the case where one or more components in a pipeline don't support reading data from HTTP object storage. By default, the property should be set to false. Each component that supports HTTP object storage should declare a similar property in its descriptor file that overrides the system property.

When the property is set to true, the WFM should copy the media to the network file share and provide a local file path to only the component services that don’t support HTTP object storage. The components that do support HTTP object storage should be provided with the HTTP URL and read the file from the object store.

Also, add a section to https://openmpf.github.io/docs/site/CPP-Batch-Component-API/index.html#component-development-best-practices that explains that, if possible, video capture should be used instead of `imread` to support media stored on a remove object storage server (HTTP and HTTPS URLs). Please mention the new descriptor.json field for declaring support for remote object storage and that it should be set to false if `imread` is used. In the future we will add that new field to https://openmpf.github.io/docs/site/Packaging-and-Registering-a-Component/index.html#component-descriptor-data-elements.

**Comment by jrobble** [comment]
Users have expressed that the current approach of copying media to a temporary file in the shared network space is acceptable. Certain media formats cannot be streamed, meaning that they would need to be copied to the shared network space anyway.

**Comment by brosenberg42** [comment]
Added in https://github.com/openmpf/openmpf/pull/845
