### ISSUE TITLE
Allow MYSQL_HOST to be set to something other than localhost

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#641]
In order to establish a JDBC connection to a mySQL instance using a hostname other than localhost, entries must be added to the mysql.user table. On  development VM, the table looks as follows:

```
mysql> select User,Host from user;
+------+-----------------------+
| User | Host                  |
+------+-----------------------+
| mpf  | %                     |
| root | 127.0.0.1             |
| root | ::1                   |
|      | localhost             |
| mpf  | localhost             |
| root | localhost             |
|      | localhost.localdomain |
| mpf  | localhost.localdomain |
| root | localhost.localdomain |
+------+-----------------------+
```

New entries must be added for other hostnames, one for each user.

Note that Docker deployments of OpenMPF have a way around this.

**Comment by clnowacki** [comment]
Things are different in Postgres. Hasn't been a problem.
