### ISSUE TITLE
Create Contributor Guide

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#69]
Publish a Contributor Guide to the OpenMPF website that covers the GitHub version control procedures. Explain that currently a MITRE dev needs to kick off the Jenkins build, which is a required check before landing the pull request.

Also, explain which repos are useful for certain kinds of developers: C++ component devs, Java component devs, WFM devs. Point to the README files that each kind of dev should use to start working with these repos.

**Comment by brosenberg42** [comment]
The GitHub help site has some relevant info.
https://help.github.com/categories/building-a-strong-community/
https://help.github.com/articles/setting-guidelines-for-repository-contributors/
