### ISSUE TITLE
Missing steps in build instructions

### ISSUE THREAD

**Issue by taa01776** [openmpf/openmpf#694]
For building APR, the directions omit the required "buildconf" step.
The instructions for installing CUDA assume the existence of /apps/source/cuda, which isn't created anywhere.

**Comment by jrobble** [comment]
In OpenMPF R3.0.0, the old packaging and deployment process is deprecated in favor of Docker deployment. Refer to the [README](https://github.com/openmpf/openmpf-docker/blob/develop/README.md#getting-started).
