### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by taa01776** [openmpf/openmpf#695]
The installation instructions (after building openmpf-*+master-0.tar.gz and copying it to a target machine) should be considerably more explicit about what the target machine prerequisites are. This can lead to interesting situations:
- The installation scripts attempt to create the "mpf" user, reporting an error if it already exists, but error out of /etc/profile.d/mpf.sh doesn't exist.
- I also get an error: could not open /opt/mpf/share/deployment_config.json for writing, at the tail end of push-configuration. Had to create the directory manually and chown it to mpf.

Obviously one can't create a keystore without Java, but that's not included in the installation instructions. If a specific version is required, then it has to be specified.

**Comment by jrobble** [comment]
In OpenMPF R3.0.0, the old packaging and deployment process is deprecated in favor of Docker deployment. Refer to the [README](https://github.com/openmpf/openmpf-docker/blob/develop/README.md#getting-started).
