### ISSUE TITLE
Bit of a circularity in installation

### ISSUE THREAD

**Issue by taa01776** [openmpf/openmpf#696]
If the mpf user exists on the installation machine with the wrong UID (not 376), installation will fail.

If not, it will be created, whereupon installation will fail because of a lack of SSH keys. An appropriate invocation of ssh-keygen at this point will allow the process to restart. The instructions should have a separate step for creating the user and SSH keys in advance of the need for them.

**Comment by jrobble** [comment]
In OpenMPF R3.0.0, the old packaging and deployment process is deprecated in favor of Docker deployment. Refer to the [README](https://github.com/openmpf/openmpf-docker/blob/develop/README.md#getting-started).
