### ISSUE TITLE
MIN_OVERLAP is not used properly in the WFM

### ISSUE THREAD

**Issue by bccole** [openmpf/openmpf#73]
The MIN_OVERLAP property is not being used when the WFM performs track merging.  Instead, in the TrackMergingProcessor, we are using only the default value pulled from the properties file:

`SortedSet<Track> newTracks = new TreeSet<Track>(combine(tracks, trackMergingPlan.getSamplingInterval(), propertiesUtil.getTrackOverlapThreshold()));`

This property is also used by the components to create their tracks -- investigation is needed into how to bring the WFM into alignment with the components.  Should there be a separate track_merging min overlap?  Note that as it stands now, if the action or job is set to more sensitive overlap than the default property, the tracks that were not merged by the component will be merged later by the WFM.

**Comment by jrobble** [comment]
Both MOG Motion and SubSENSE motion use TRACKING_MIN_OVERLAP_PERCENTAGE. How does that differ from MIN_OVERLAP? We may may to use the latter instead for consistency.
