### ISSUE TITLE
Revise Build Guide and Install Guide for Docker deployment

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#759]
The Build Guide and Install Guide currently have warnings saying that the steps are deprecated in favor of Docker deployment. Remove the deprecated content and update the guides to be more relevant. Don't repeat what is already stated in the openmpf-docker README and SWARM files.

Of note, in the Build Guide, discuss how a developer could refer to the steps in the openmpf_build `Dockerfile` to setup a development VM. In the Install Guide, discuss how a user could use the the `docker-compose-save.sh` and `docker-compose-load.sh` scripts to create a .tar.gz file for distribution and deployment in environments without Internet / Docker registry access.

This is related to https://github.com/openmpf/openmpf/issues/761.

**Comment by clnowacki** [comment]
To make it clear that the old build guide is deprecated, we need to put the Docker build and deployment documentation on the openmpf.github.io site, and make it difficult for people to find the old build guide.
