### ISSUE TITLE
Make better use of `jobErrors` and `jobWarnings` fields in JSON output object

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#780]
Make better use of `jobErrors` and `jobWarnings` fields in JSON output object. Consumers of the JSON output object will use the content of these fields to display high-level information to end users. The content of these fields should capture all possible error and warning conditions and provide a high-level summary of the issue(s).

When there is a detectionProceesingError, the top-level `jobErrors` field states "Some components had errors for some media. Refer to the detectionProcessingErrors fields." We should not refer to other fields in the `jobErrors` and `jobWarnings` fields. Instead, the messages should make sense on their own. Also, if multiple segments had the same issue for a single piece of media, that should be summarized in one `jobErrors` entry that lists the segment ranges with the issue.

---

Every error and warning should be paired with a short string "code" that the JSON consumer can use to quickly determine the nature of the issue without parsing the message string directly. 

Each error and warning should be accompanied by a media id. One way to do this is group the errors and warnings by media id.

This is related to https://github.com/openmpf/openmpf/issues/767 and https://github.com/openmpf/openmpf/issues/812.

**Comment by jrobble** [comment]
From users: "leave both the artifactExtractionResults and markupResults set to null if not attempted".

**Comment by jrobble** [comment]
As stated in the task, our goal is to eventually summarize everything at the top-level with `jobErrors` and `jobWarnings`, and also to provide more detailed information at the media-level in the JSON.
So at the media level we can report artifact extraction errors in an artifact extraction section, markup errors in a markup section, detection processing errors in that section, and other errors in the `media.status` and `media.message` section. The reason for reporting artifact extraction and markup errors separately is that we already have separate parts in the JSON where we report those file paths.
Detection processing errors reports the segment frames and times.

**Comment by jrobble** [comment]
From end users:

> Jobs marked as ERROR don't have any messages in the "jobErrors" field.

When a job has an `*ERROR*` or `*WARNING*` status, it should have at least one entry in `jobErrors` or `jobWarnings`, respectively.

**Comment by clnowacki** [comment]
Job errors will be grouped by media. The structure associated with each error will have 3 fields:

```
"jobErrors" : {
    "media": [
         {
            "mediaId": 1
            "mediaErrors: [
                { "code": "DEAD_LETTER",
                "message": "detailed message",
                "source": "WORKFLOW MANAGER" },   
                { "code": "GPU_ERROR",
                "message": "detailed message",
                 "source": "DARKNET COMPONENT" }
              ]
          }
       ]
    }
```

**Comment by brosenberg42** [comment]
Structure will be:
```
{
   "errors": [
      {
         "details": [
            {
               "source": "WORKFLOW_MANAGER",
               "code": "SOME_JOB_WIDE_ERROR",
               "message": "Some job wide error message."
            }
         ]
      },
      {
         "mediaId": 1,
         "details": [
            {
               "source": "FACECV",
               "code": "SOME_ERROR",
               "message": "Some error message (Frames: 500 - 1499, 4000 - 4499, 5000 - 19975)"
            }
         ]
      }
   ],
   "warnings": [
      {
         "mediaId": 1,
         "details": [
            {
               "source": "WORKFLOW_MANAGER",
               "code": "SOME_WARNING",
               "message": "Some warning message"
            }
         ]
      }
   ],
}
```
