### ISSUE TITLE
Generate JSON.Output.Examples.tar.gz and openmpf-interop-3.0.0.tar.gz with JSON changes

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#786]
The example JSON in output examples package needs to be updated:
- Remove redundant *Offset fields from the output JSON in favor of *Frame fields.
- Addition of `jobErrors` and `jobWarnings` fields.

Also, running openmpf/trunk/interop/src/test/java/org/mitre/mpf/SchemaCreator.java produces a JsonOutputObject.schema.json with the following content:

```
    "jobErrors" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "jobWarnings" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
```

We need to add meaningful descriptions to those fields and regenerate openmpf-interop-3.0.0.tar.gz.

Upload the new JSON.Output.Examples.tar.gz package and openmpf-interop-3.0.0.tar.gz package to the openmpf repo r3.0.0-rc1 preview release: https://github.com/openmpf/openmpf/releases

Related to https://github.com/openmpf/openmpf/issues/785.

**Comment by brosenberg42** [comment]
The release files have been updated. PR #788 contains the changes that add @JsonPropertyDescription to JsonOutputObject's "jobErrors" and "jobWarnings"
