### ISSUE TITLE
Investigate YOLO 9000 support

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#791]
> Is YOLO 9000 supported in the current version of Darknet used by the Darknet component?

No. @brosenberg42 tried to use [this weights file](
https://pjreddie.com/media/files/yolo9000.weights) and ran into a segfault: _"It segfaults whether I run it through the binary from the original author or through our component."_

> What steps would be necessary to support YOLO 9000?

It seems that our options are:
 
- Perform our own training using the current version of Darknet.
- Revert back to an older version of Darknet (YoloV2) that’s compatible with the provided weights file.

**Comment by clnowacki** [comment]
Darknet component has been archived.
