### ISSUE TITLE
Avoid getting entire Redis collection when only one element is needed.

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#797]
For example, https://github.com/openmpf/openmpf/blob/develop/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java#L1229 retrieves the whole set instead of just calling `isMember()`.

**Comment by jrobble** [comment]
We moved away from using Redis to store transient data for everything but tracks.
