### ISSUE TITLE
Avoid unnecessary serialization between Camel routes 

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#799]
Whenever an object needs to be sent from one route to another or between processors in a single route, it gets serialized in the Smile format. The objects are only used within the WFM JVM so serialization is unnecessary.

**Comment by jrobble** [comment]
As an alternative to serialization, we should consider avoiding multiple Camel processors for functionality that is all performed by the WFM - this may be accomplished using method calls instead.
