### ISSUE TITLE
Investigate AttenScriptNetPR TensorFlow models for script identification

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#842]
Investigate the [AttenScriptNetPR](https://github.com/ankanbhunia/AttenScriptNetPR) TensorFlow models for script identification.

**Comment by hhuangMITRE** [comment]
The AttenScriptNetPR repo contains four different models trained on the following script classification datasets:
* CVSI-2015 : English, Hindi(Devnagari), Bengali(Bangla), Oriya, Gujrathi, Punjabi, Kannada, Tamil, Telegu, and Arabic
* SIW-13 : Arabic, Cambodian, Chinese, English, Greek, Hebrew, Japanese, Kannada, Korean, Mongolian, Russian, Thai, and Tibetan
* ICDAR-2017 : Arabic, Bangla, Chinese, English, French, German, Italian, Japanese and Korean
* MLe2e : Latin, Chinese, Kannada, and Hangul

Overall, most of the classification datasets supported 10 or fewer unique scripts.
Expanding existing models to identify new scripts would require building a much larger script classification dataset, which is currently unfeasible.
