### ISSUE TITLE
Remove common WFM properties from component descriptor.json files

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#866]
Currently, many properties that are only used by the WFM and/or the MPFImageReader/MPFVideoCapture tools are represented in many component descriptor.json files, which is very redundant. For example, here are the common properties for components that support the VIDEO data type:

- FEED_FORWARD_TYPE
- FEED_FORWARD_TOP_CONFIDENCE_COUNT
- USE_KEY_FRAMES
- FRAME_INTERVAL
- FRAME_RATE_CAP
- CONFIDENCE_THRESHOLD
- MIN_GAP_BETWEEN_SEGMENTS
- TARGET_SEGMENT_LENGTH
- MIN_SEGMENT_LENGTH
- MERGE_TRACKS
- MIN_GAP_BETWEEN_TRACKS
- MIN_TRACK_LENGTH
- MIN_OVERLAP
- SEARCH_REGION_ENABLE_DETECTION
- SEARCH_REGION_TOP_LEFT_X_DETECTION
- SEARCH_REGION_TOP_LEFT_Y_DETECTION
- SEARCH_REGION_BOTTOM_RIGHT_X_DETECTION
- SEARCH_REGION_BOTTOM_RIGHT_Y_DETECTION
- ROTATION
- HORIZONTAL_FLIP
- AUTO_ROTATE
- AUTO_FLIP

There is a smaller set of properties for the IMAGE data type:

- FEED_FORWARD_TYPE
- CONFIDENCE_THRESHOLD
- SEARCH_REGION_ENABLE_DETECTION
- SEARCH_REGION_TOP_LEFT_X_DETECTION
- SEARCH_REGION_TOP_LEFT_Y_DETECTION
- SEARCH_REGION_BOTTOM_RIGHT_X_DETECTION
- SEARCH_REGION_BOTTOM_RIGHT_Y_DETECTION
- ROTATION
- HORIZONTAL_FLIP
- AUTO_ROTATE
- AUTO_FLIP

Note that all component types (VIDEO, IMAGE, AUDIO, UNKNOWN) need to support:

- CONFIDENCE_THRESHOLD

There are some exceptions to this rule. For example, the Sphinx component supports both VIDEO and AUDIO types; however, it just generates a .wav file from the video file, so most of the VIDEO properties in the first list don't apply. Only CONFIDENCE_THRESHOLD makes sense. 

That said, when a component supports both VIDEO and AUDIO, use the list of properties for AUDIO. When a component supports both VIDEO and IMAGE, use the list of properties for VIDEO. More succinctly, when a component supports multiple data types, use the list of properties that correspond to the first supported type from this list:

1. UNKNOWN (CONFIDENCE_THRESHOLD only)
2. AUDIO (CONFIDENCE_THRESHOLD only)
3. VIDEO
4. IMAGE

Instead of representing these properties in each component's descriptor.json, they should be handled by the WFM. That means, these properties should be defined in a separate, common, config file managed by the WFM. It may make sense to have one config file per data type.

1. When a job is created, the WFM will determine which properties it should apply based on the data type for that job and the data types the component supports `*`. Specifically, the WFM will provide the default system property values if the properties are not defined as a job, algorithm, media, or pipeline (action) property. 

2. When creating a pipeline through the WFM UI, the WFM should allow the user to specify the values for the properties that are applicable to that component `*`.

`*` In order to do this, the WFM needs to know which data types the component supports. Those may need to be defined in the descriptor.json itself: https://github.com/openmpf/openmpf/issues/963. Currently, the only way to get that information is by executing the component `Supports()` function (or in the case of Python, whether or not a method is defined). The WFM does not execute the component code itself, so that is not an option.

**Comment by jrobble** [comment]
Additionally, ARTIFACT_EXTRACTION_POLICY should be added to the lists for IMAGE and VIDEO data types (https://github.com/openmpf/openmpf/issues/344).

The following system properties are described in https://github.com/openmpf/openmpf/issues/511:

1. detection.artifact.extraction.policy.exemplar.frame 
2. detection.artifact.extraction.policy.first.frame
3. detection.artifact.extraction.policy.middle.frame
4. detection.artifact.extraction.policy.last.frame 
5. detection.artifact.extraction.policy.top.confidence.count
6. detection.artifact.extraction.policy.exemplar.before.after.count

The corresponding job properties should be added to the lists for IMAGE and VIDEO data types as well.

While we're at it, the following job properties that determine the content of the JSON output object should be added to the lists for all data types (https://github.com/openmpf/openmpf/issues/752):

- OUTPUT_EXEMPLARS_ONLY
- OUTPUT_LAST_STAGE_ONLY

**Comment by clnowacki** [comment]
To be exact, the detection.artifact.extraction.policy.exemplar.frame and detection.artifact.extraction.policy.exemplar.before.after.count properties have been combined into one property, detection.artifact.extraction.policy.exemplar.frame.plus, as per the customer request. I will add a note to issue 511 to update it.
