### ISSUE TITLE
Upgrade ActiveMQ

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#885]
Upgrade ActiveMQ from 5.13 to 5.15.9, the latest and greatest. Determine if that breaks anything.

This is done in attempt to address https://github.com/openmpf/openmpf/issues/745.

**Comment by clnowacki** [comment]
Upgrading from 5.13 to 5.15.9 on my development VM worked fine. I was able to run the web UI with multiple components and multiple jobs running in parallel, and everything completed successfully. I was also able to stop and restart the system without any issues.
