### ISSUE TITLE
Tesseract component reports wrong top-left coordinate for non-zero ROTATION values

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#904]
When we talk about top-left coordinate in the MPFImageLocation, top-left is what the component believes the top-left of the detection region should be. So, if the component believes that the detection region is rotated 180 degrees, the top-left coordinate for the MPFImageLocation should actually be the coordinate that corresponds to the bottom-right of the OpenCV Mat you’re processing. If the component believes that the detection region is rotated 90 degrees CCW, then the top-left coordinate for the MPFImageLocation should actually be the coordinate that corresponds to the bottom-left of the OpenCV Mat. 270 degrees CCW would be the top-right.

**Comment by hhuangMITRE** [comment]
Ah I see, I'll update the component to provide the top-right coordinate based on the OSD rotation predictions then. That should be patched in later today, thanks for catching that!
