### ISSUE TITLE
Quotes in algorithm property descriptions are not displaying properly

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#910]
In the Pipelines and Pipelines 2 web UI, the double quotes around `NONE` appear as question marks:

```
Only applies if FEED_FORWARD_TYPE is set to a value other than “NONE”. If set to a value <= 0, then for each track generated in the previous pipeline stage, this algorithm will process the frame associated with each detection in that track, ignoring frames that don’t have detections.
```

There are a number of other places, related to the content of the descriptor.json files, where this happens. This was observed on FireFox.

**Comment by bquinn17** [comment]
I was not able to reproduce this in Firefox version 60.7.2esr (64-bit) on Centos. The output displayed with normal quotation marks and not with question marks.
