### ISSUE TITLE
Update /pipelines?name REST endpoint to appear in Swagger

### ISSUE THREAD

**Issue by brosenberg42** [openmpf/openmpf#949]
Swagger can't show both GET `/pipelines` and GET `/pipelines?name=MYPIPELINE`. Updating to Swagger 3 did not resolve this issue. From [here](https://swagger.io/docs/specification/paths-and-operations/):

> This also means that it is impossible to have multiple paths that differ only in query string, such as:

```
    GET /users?firstName=value&lastName=value
    GET /users?role=value
```

> This is because OpenAPI considers a unique operation as a combination of a path and the HTTP method, and additional parameters do not make the operation unique.

To address this, instead of `/pipelines?name=MYPIPELINE` we could change the REST endpoint to `/pipelines/MYPIPELINE`; however, that will disallow certain characters in pipeline names. We would need to test it to determine the exact set of characters. The one that caused us problems initially was slash. Spring won't accept the percent encoded slash.

Moving forward, we should ensure that all future exposed endpoints appear in Swagger.

**Comment by jrobble** [comment]
According to https://github.com/springfox/springfox/pull/2153#issuecomment-420640640, Springfox version >= 2.8.0 supports Swagger 3.
