### ISSUE TITLE
Auto configure Kibana index

### ISSUE THREAD

**Issue by bquinn17** [openmpf/openmpf#954]
Currently a user must manually create an index pattern in the Kibana web UI every time the ELK container is created (or recreated). 

It would be nice if we could create this index in an automated way, in order to skip this step.
https://stackoverflow.com/questions/36871862/programmatically-set-kibanas-default-index-pattern

This is what the pattern looks like when created from the UI. `"index-pattern" : { "title" : "filebeat-*", "timeFieldName" : "@timestamp", "type" : "index-pattern" }`

**Comment by jrobble** [comment]
@brosenberg42 looked into this. It's not worth the trouble.
