### ISSUE TITLE
Document REST endpoints for creating and removing actions, tasks, and pipelines

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#964]
Document the REST endpoints exposed in https://github.com/openmpf/openmpf/issues/937 in the github.io REST API doc.

**Comment by mawentowski** [comment]
I am a technical writer looking to join an open source project to document RESTful APIs. I currently have 7 years experience as a technical writer that includes experience with "docs as code" workflows, Git, and static sites. I am venturing into the world of APIs and was wondering if you currently have any tasks you need assistance with?

**Comment by jrobble** [comment]
Hi @mawentowski, thanks for reaching out! Currently we generate documentation from our program's live Swagger page ([screenshot](https://openmpf.github.io/docs/site/User-Guide/index.html#rest-api)) and turn it into static HTML like [this](https://openmpf.github.io/docs/site/html/REST-API.html). 

If you're interested in building and deploying a local Docker version of OpenMPF so that you can view the Swagger page and help generate the HTML, or have other ideas, let us know.

We also have this task for cleaning up the REST endpoints if you actually want to get involved in how the Swagger page is generated and touch some Java Spring code: https://github.com/openmpf/openmpf/issues/971

**Comment by mawentowski** [comment]
Hey @jrobble, thanks for the quick reply. Yes, I am definitely interested in deploying the local Docker version to help generate the HTML. I'd have to learn some of your basic flows/processes, as well as which static site generator you are using. Currently I have experience working with Jekyll.

I am also interested in the REST endpoint cleanup. I'll read up on your static site content and the endpoints issue to get up-to-speed on your API.
