### ISSUE TITLE
Add S3_* properties to workflow-properties.json

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#977]
Add the following S3_* properties to `workflow-properties.json`:

- S3_RESULTS_BUCKET
- S3_UPLOAD_ONLY
- S3_ACCESS_KEY
- S3_SECRET_KEY

**Comment by lmtoothman** [comment]
@jrobble I think this is all we need for the change in object storage access. I'm assuming if these properties are added to the JSON we could specify default values for each deployment.

**Comment by jrobble** [comment]
@lmtoothman These system properties values will be added to the `mpf.properties` file, so you could hardcode the defaults in the repo in the same way we're hard-coding defaults for other system property values for your deployment purposes. The customizations end up in the `$MPF_HOME/share/config/mpf-custom.properties` file, which you can override using a 'docker config', if you want.
